/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.84
 * Generated at: 2018-03-27 01:58:13 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.business.saleback;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.util.*;

public final class saleBack_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "/inc.jsp", out, false);
      out.write("\r\n");
      out.write("<script type=\"text/javascript\" charset=\"utf-8\">\r\n");
      out.write("    var searchForm;\r\n");
      out.write("\tvar datagrid;\r\n");
      out.write("\tvar cdescAdd;\r\n");
      out.write("\tvar cdescEdit;\r\n");
      out.write("\tvar showCdescDialog;\r\n");
      out.write("\tvar iframeDialog;\r\n");
      out.write("\tvar datagridSale;\r\n");
      out.write("\t$(function() {\r\n");
      out.write("\t    $('#iframeDialog').css('width',(window.screen.width - 200)>1000?1000:(window.screen.width - 200));\r\n");
      out.write("\t    $('#iframeDialog').attr('height',window.screen.height - 60);\r\n");
      out.write("\t    //查询列表\t\r\n");
      out.write("\t    searchForm = $('#searchForm').form();\r\n");
      out.write("\t    datagridSale = $('#datagridSale').datagrid({\r\n");
      out.write("\t\t\turl : 'saleAction!datagrid.action',\r\n");
      out.write("\t\t\ttitle : '销售单列表',\r\n");
      out.write("\t\t\ticonCls : 'icon-save',\r\n");
      out.write("\t\t\tpagination : true,\r\n");
      out.write("\t\t\tpagePosition : 'bottom',\r\n");
      out.write("\t\t\trownumbers : true,\r\n");
      out.write("\t\t\tpageSize : 3,\r\n");
      out.write("\t\t\tpageList : [ 3,10, 20, 30, 40 ],\r\n");
      out.write("\t\t\tfit : true,\r\n");
      out.write("\t\t\tfitColumns : false,\r\n");
      out.write("\t\t\tsingleSelect:true,\r\n");
      out.write("\t\t\tnowrap : true,\r\n");
      out.write("\t\t\tborder : false,\r\n");
      out.write("\t\t\tidField : 'salebillno',\r\n");
      out.write("\t\t\tsortName : 'createdate',\r\n");
      out.write("\t\t\tsortOrder : 'desc',\r\n");
      out.write("\t\t\tcolumns : [ [ \r\n");
      out.write("\t\t\t{field:'ck',checkbox:true,\r\n");
      out.write("\t\t\t\t\t\tformatter:function(value,row,index){\r\n");
      out.write("\t\t\t\t\t\t\treturn row.salebillno;\r\n");
      out.write("\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t},\r\n");
      out.write("\t\t\t   {field:'salebillno',title:'销售单号',align:'center',sortable:true,width:100,\r\n");
      out.write("\t\t\t\t\tformatter:function(value,row,index){\r\n");
      out.write("\t\t\t\t\t\treturn '<a href=\\'#\\' onclick=\\'detailSaleBillDetail('+row.salebillno+')\\' >'+row.salebillno+'</a>';\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t},\t\t\t\t\r\n");
      out.write("\t\t\t   {field:'amount',title:'销售金额',align:'center',sortable:true,width:80,\r\n");
      out.write("\t\t\t\t\tformatter:function(value,row,index){\r\n");
      out.write("\t\t\t\t\t\treturn row.amount;\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t},\t\t\t\t\r\n");
      out.write("\t\t\t   {field:'customerid',title:'销售客户',align:'center',sortable:true,width:100,\r\n");
      out.write("\t\t\t\t\tformatter:function(value,row,index){\r\n");
      out.write("\t\t\t\t\t\treturn row.customerpage.customername;\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t},\t\t\t\t\r\n");
      out.write("\t\t\t   {field:'saledate',title:'销售日期',align:'center',sortable:true,width:80,\r\n");
      out.write("\t\t\t\t\tformatter:function(value,row,index){\r\n");
      out.write("\t\t\t\t\t\treturn dateFormatYMD(row.saledate);\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t},\t\t\t\t\r\n");
      out.write("\t\t\t   {field:'accountid',title:'业务员',align:'center',sortable:true,width:60,\r\n");
      out.write("\t\t\t\t\tformatter:function(value,row,index){\r\n");
      out.write("\t\t\t\t\t\treturn row.accounterpage.accountname;\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t},\t\t\t\t\r\n");
      out.write("\t\t\t   {field:'salerate',title:'提成比例',align:'center',sortable:true,width:70,\r\n");
      out.write("\t\t\t\t\tformatter:function(value,row,index){\r\n");
      out.write("\t\t\t\t\t\treturn row.salerate;\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t},\t\t\t\t\r\n");
      out.write("\t\t\t   {field:'isreceive',title:'是否收款',align:'center',hidden:true,sortable:true,width:60,\r\n");
      out.write("\t\t\t\t\tformatter:function(value,row,index){\r\n");
      out.write("\t\t\t\t\t\treturn dictGetName('004',row.isreceive);\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t},\t\t\t\t\r\n");
      out.write("\t\t\t   {field:'crtusername',title:'操作人姓名',align:'center',sortable:true,width:80,\r\n");
      out.write("\t\t\t\t\tformatter:function(value,row,index){\r\n");
      out.write("\t\t\t\t\t\treturn row.crtusername;\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t},\t\t\t\t\r\n");
      out.write("\t\t\t   {field:'modifydate',title:'修改日期',align:'center',sortable:true,width:110,\r\n");
      out.write("\t\t\t\t\tformatter:function(value,row,index){\r\n");
      out.write("\t\t\t\t\t\treturn row.modifydate;\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t},\t\t\t\t\r\n");
      out.write("\t\t\t   {field:'createdate',title:'创建日期',align:'center',sortable:true,width:110,\r\n");
      out.write("\t\t\t\t\tformatter:function(value,row,index){\r\n");
      out.write("\t\t\t\t\t\treturn row.createdate;\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t},\t\r\n");
      out.write("\t\t\t\t{field:'salebackbillitems',title:'销售退货单列表',align:'center',sortable:true,width:110,\r\n");
      out.write("\t\t\t\t\tformatter:function(value,row,index){\r\n");
      out.write("\t\t\t\t\t    if (row.salebackbillitems!=null&&row.salebackbillitems!=\"\")\r\n");
      out.write("\t\t\t\t\t\t    return '<span title='+row.salebackbillitems+'>'+row.salebackbillitems+'</span>';\r\n");
      out.write("\t\t\t\t\t\telse return row.salebackbillitems;\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t},\r\n");
      out.write("\t\t\t\t{field:'meno',title:'备注',align:'center',sortable:true,width:100,\r\n");
      out.write("\t\t\t\t\tformatter:function(value,row,index){\r\n");
      out.write("\t\t\t\t\t\treturn row.meno;\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t}\t\t\t\t\r\n");
      out.write("\t\t\t ] ],\r\n");
      out.write("\t\t\tonRowContextMenu : function(e, rowIndex, rowData) {\r\n");
      out.write("\t\t\t\te.preventDefault();\r\n");
      out.write("\t\t\t\t$(this).datagrid('unselectAll');\r\n");
      out.write("\t\t\t\t$(this).datagrid('selectRow', rowIndex);\r\n");
      out.write("\t\t\t\t$('#menuTop').menu('show', {\r\n");
      out.write("\t\t\t\t\tleft : e.pageX,\r\n");
      out.write("\t\t\t\t\ttop : e.pageY\r\n");
      out.write("\t\t\t\t});\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t});\r\n");
      out.write("\t\tdatagrid = $('#datagrid').datagrid({\r\n");
      out.write("\t\t\turl : 'saleBackAction!datagrid.action',\r\n");
      out.write("\t\t\ttitle : '销售退货单列表',\r\n");
      out.write("\t\t\ticonCls : 'icon-save',\r\n");
      out.write("\t\t\tpagination : true,\r\n");
      out.write("\t\t\tpagePosition : 'bottom',\r\n");
      out.write("\t\t\trownumbers : true,\r\n");
      out.write("\t\t\tpageSize : 5,\r\n");
      out.write("\t\t\tpageList : [5, 10, 20, 30, 40 ],\r\n");
      out.write("\t\t\tfit : true,\r\n");
      out.write("\t\t\tsingleSelect:true,\r\n");
      out.write("\t\t\tfitColumns : false,\r\n");
      out.write("\t\t\tnowrap : true,\r\n");
      out.write("\t\t\tborder : false,\r\n");
      out.write("\t\t\tidField : 'salebackno',\r\n");
      out.write("\t\t\tsortName : 'createdate',\r\n");
      out.write("\t\t\tsortOrder : 'desc',\r\n");
      out.write("\t\t\tcolumns : [ [ \r\n");
      out.write("\t\t\t{field:'ck',checkbox:true,\r\n");
      out.write("\t\t\t\t\t\tformatter:function(value,row,index){\r\n");
      out.write("\t\t\t\t\t\t\treturn row.salebackno;\r\n");
      out.write("\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t},\r\n");
      out.write("\t\t\t   {field:'salebackno',title:'销售退货单号',align:'center',sortable:true,width:90,\r\n");
      out.write("\t\t\t\t\tformatter:function(value,row,index){\r\n");
      out.write("\t\t\t\t\t\treturn row.salebackno;\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t},\t\t\t\t\r\n");
      out.write("\t\t\t   {field:'salebillno',title:'原销售单号',align:'center',sortable:true,width:90,\r\n");
      out.write("\t\t\t\t\tformatter:function(value,row,index){\r\n");
      out.write("\t\t\t\t\t\treturn row.salebillno;\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t},\t\t\t\t\r\n");
      out.write("\t\t\t   {field:'customerid',title:'退货客户',align:'center',sortable:true,width:90,\r\n");
      out.write("\t\t\t\t\tformatter:function(value,row,index){\r\n");
      out.write("\t\t\t\t\t\treturn row.customerpage.customername;\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t},\t\t\t\t\r\n");
      out.write("\t\t\t   {field:'backdate',title:'退货日期',align:'center',sortable:true,width:70,\r\n");
      out.write("\t\t\t\t\tformatter:function(value,row,index){\r\n");
      out.write("\t\t\t\t\t\treturn dateFormatYMD(row.backdate);\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t},\t\t\t\t\r\n");
      out.write("\t\t\t   {field:'accountid',title:'业务员',align:'center',sortable:true,width:70,\r\n");
      out.write("\t\t\t\t\tformatter:function(value,row,index){\r\n");
      out.write("\t\t\t\t\t\treturn row.accounterpage.accountname;\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t},\t\t\t\t\r\n");
      out.write("\t\t\t   {field:'salerate',title:'原提成比例',align:'center',sortable:true,width:80,\r\n");
      out.write("\t\t\t\t\tformatter:function(value,row,index){\r\n");
      out.write("\t\t\t\t\t\treturn row.salerate;\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t},\t\t\t\t\r\n");
      out.write("\t\t\t   \t\t\t\t\r\n");
      out.write("\t\t\t   {field:'isreceive',title:'是否收款',align:'center',hidden:true,sortable:true,width:80,\r\n");
      out.write("\t\t\t\t\tformatter:function(value,row,index){\r\n");
      out.write("\t\t\t\t\t\treturn dictGetName('004',row.isreceive);\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t},\t\t\t\t\r\n");
      out.write("\t\t\t   {field:'crtusername',title:'操作人姓名',align:'center',sortable:true,width:80,\r\n");
      out.write("\t\t\t\t\tformatter:function(value,row,index){\r\n");
      out.write("\t\t\t\t\t\treturn row.crtusername;\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t},\t\t\t\t\r\n");
      out.write("\t\t\t   {field:'modifydate',title:'修改日期',align:'center',sortable:true,width:110,\r\n");
      out.write("\t\t\t\t\tformatter:function(value,row,index){\r\n");
      out.write("\t\t\t\t\t\treturn row.modifydate;\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t},\t\t\t\t\r\n");
      out.write("\t\t\t   {field:'createdate',title:'创建日期',align:'center',sortable:true,width:110,\r\n");
      out.write("\t\t\t\t\tformatter:function(value,row,index){\r\n");
      out.write("\t\t\t\t\t\treturn row.createdate;\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t},\t\t\t\t\r\n");
      out.write("\t\t\t   {field:'amount',title:'退货金额',align:'center',sortable:true,width:70,\r\n");
      out.write("\t\t\t\t\tformatter:function(value,row,index){\r\n");
      out.write("\t\t\t\t\t\treturn row.amount;\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t},\r\n");
      out.write("\t\t\t\t{field:'meno',title:'备注',align:'center',sortable:true,width:110,\r\n");
      out.write("\t\t\t\t\tformatter:function(value,row,index){\r\n");
      out.write("\t\t\t\t\t\treturn row.meno;\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t}\t\t\t\r\n");
      out.write("\t\t\t ] ],\r\n");
      out.write("\t\t\ttoolbar : [ {\r\n");
      out.write("\t\t\t\ttext : '增加销售退货单',\r\n");
      out.write("\t\t\t\ticonCls : 'icon-add',\r\n");
      out.write("\t\t\t\thandler : function() {\r\n");
      out.write("\t\t\t\t\tadd();\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t},  '-', {\r\n");
      out.write("\t\t\t\ttext : '查看销售退货单',\r\n");
      out.write("\t\t\t\ticonCls : 'icon-edit',\r\n");
      out.write("\t\t\t\thandler : function() {\r\n");
      out.write("\t\t\t\t\tdetail();\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t}, '-', {\r\n");
      out.write("\t\t\t\ttext : '取消选中',\r\n");
      out.write("\t\t\t\ticonCls : 'icon-undo',\r\n");
      out.write("\t\t\t\thandler : function() {\r\n");
      out.write("\t\t\t\t\tdatagrid.datagrid('unselectAll');\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t}, '-' ],\r\n");
      out.write("\t\t\tonRowContextMenu : function(e, rowIndex, rowData) {\r\n");
      out.write("\t\t\t\te.preventDefault();\r\n");
      out.write("\t\t\t\t$(this).datagrid('unselectAll');\r\n");
      out.write("\t\t\t\t$(this).datagrid('selectRow', rowIndex);\r\n");
      out.write("\t\t\t\t$('#menuBottom').menu('show', {\r\n");
      out.write("\t\t\t\t\tleft : e.pageX,\r\n");
      out.write("\t\t\t\t\ttop : e.pageY\r\n");
      out.write("\t\t\t\t});\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t});\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\tcdescAdd = $('#cdescAdd').xheditor({\r\n");
      out.write("\t\t\ttools : 'mini',\r\n");
      out.write("\t\t\thtml5Upload : true,\r\n");
      out.write("\t\t\tupMultiple : 4,\r\n");
      out.write("\t\t\tupLinkUrl : 'saleBackAction!upload.action',\r\n");
      out.write("\t\t\tupLinkExt : 'zip,rar,txt,doc,docx,xls,xlsx',\r\n");
      out.write("\t\t\tupImgUrl : 'saleBackAction!upload.action',\r\n");
      out.write("\t\t\tupImgExt : 'jpg,jpeg,gif,png'\r\n");
      out.write("\t\t});\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\tcdescEdit = $('#cdescEdit').xheditor({\r\n");
      out.write("\t\t\ttools : 'mini',\r\n");
      out.write("\t\t\thtml5Upload : true,\r\n");
      out.write("\t\t\tupMultiple : 4,\r\n");
      out.write("\t\t\tupLinkUrl : 'saleBackAction!upload.action',\r\n");
      out.write("\t\t\tupLinkExt : 'zip,rar,txt,doc,docx,xls,xlsx',\r\n");
      out.write("\t\t\tupImgUrl : 'saleBackAction!upload.action',\r\n");
      out.write("\t\t\tupImgExt : 'jpg,jpeg,gif,png'\r\n");
      out.write("\t\t});\r\n");
      out.write("\r\n");
      out.write("\t\tshowCdescDialog = $('#showCdescDialog').show().dialog({\r\n");
      out.write("\t\t\ttitle : '销售退货单描述',\r\n");
      out.write("\t\t\tmodal : true,\r\n");
      out.write("\t\t\tclosed : true,\r\n");
      out.write("\t\t\tmaximizable : true\r\n");
      out.write("\t\t});\r\n");
      out.write("\r\n");
      out.write("\t\tiframeDialog = $('#iframeDialog').show().dialog({\r\n");
      out.write("\t\t\ttitle : 'POP弹出页面',\r\n");
      out.write("\t\t\tmodal : true,\r\n");
      out.write("\t\t\tclosed : true,\r\n");
      out.write("\t\t\tmaximizable : true,\r\n");
      out.write("\t\t\tonClose : function(){\r\n");
      out.write("\t\t\t    document.getElementById(\"iframe\").src = \"about:blank\";\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t});\r\n");
      out.write("\t});\r\n");
      out.write("\r\n");
      out.write("\tfunction _search() {\r\n");
      out.write("\t\tdatagridSale.datagrid('load', sy.serializeObject(searchForm));\r\n");
      out.write("\t}\r\n");
      out.write("\tfunction cleanSearch() {\r\n");
      out.write("\t\tdatagridSale.datagrid('load', {});\r\n");
      out.write("\t\tsearchForm.find('input').val('');\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\tfunction add() {\r\n");
      out.write("\t\tvar rows = datagridSale.datagrid('getSelections');\r\n");
      out.write("\t\tif (rows.length == 1) {\r\n");
      out.write("\t\t    $('#iframeDialog').dialog('setTitle', '新建销售退货单'); \r\n");
      out.write("\t\t    iframeDialog.dialog('open');\r\n");
      out.write("\t\t    $(\"#loading\").css(\"display\",\"block\");\r\n");
      out.write("\t\t    document.getElementById(\"iframe\").src = \"saleBackAction!toSaleBackMainAdd.action?salebillno=\"+rows[0].salebillno;\r\n");
      out.write("\t\t} else {\r\n");
      out.write("\t\t\t$.messager.alert('提示', '请选择一项要退货的销售单！', 'error');\r\n");
      out.write("\t\t}\r\n");
      out.write("\t}\r\n");
      out.write("\tfunction del() {\r\n");
      out.write("\t\tvar rows = datagrid.datagrid('getSelections');\r\n");
      out.write("\t\tvar ids = [];\r\n");
      out.write("\t\tif (rows.length > 0) {\r\n");
      out.write("\t\t\t$.messager.confirm('请确认', '您要删除当前所选项目？', function(r) {\r\n");
      out.write("\t\t\t\tif (r) {\r\n");
      out.write("\t\t\t\t\tfor ( var i = 0; i < rows.length; i++) {\r\n");
      out.write("\t\t\t\t\t\tids.push(rows[i].salebackno);\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t$.ajax({\r\n");
      out.write("\t\t\t\t\t\turl : 'saleBackAction!delete.action',\r\n");
      out.write("\t\t\t\t\t\tdata : {\r\n");
      out.write("\t\t\t\t\t\t\tids : ids.join(',')\r\n");
      out.write("\t\t\t\t\t\t},\r\n");
      out.write("\t\t\t\t\t\tdataType : 'json',\r\n");
      out.write("\t\t\t\t\t\tsuccess : function(response) {\r\n");
      out.write("\t\t\t\t\t\t\tdatagrid.datagrid('load');\r\n");
      out.write("\t\t\t\t\t\t\tdatagrid.datagrid('unselectAll');\r\n");
      out.write("\t\t\t\t\t\t\t$.messager.show({\r\n");
      out.write("\t\t\t\t\t\t\t\ttitle : '提示',\r\n");
      out.write("\t\t\t\t\t\t\t\tmsg : '删除成功！'\r\n");
      out.write("\t\t\t\t\t\t\t});\r\n");
      out.write("\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t});\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t});\r\n");
      out.write("\t\t} else {\r\n");
      out.write("\t\t\t$.messager.alert('提示', '请选择要删除的记录！', 'error');\r\n");
      out.write("\t\t}\r\n");
      out.write("\t}\r\n");
      out.write("\tfunction edit() {\r\n");
      out.write("\t\tvar rows = datagrid.datagrid('getSelections');\r\n");
      out.write("\t\tif (rows.length == 1) {\r\n");
      out.write("\t\t\t$('#iframeDialog').dialog('setTitle', '编辑销售退货单'); \r\n");
      out.write("\t\t\tiframeDialog.dialog('open');\r\n");
      out.write("\t\t\t$(\"#loading\").css(\"display\",\"block\");\r\n");
      out.write("\t\t\tdocument.getElementById(\"iframe\").src = \"saleBackAction!toSaleBackMainEdit.action?salebackno=\"+rows[0].salebackno;\r\n");
      out.write("\t\t} else {\r\n");
      out.write("\t\t\t$.messager.alert('提示', '请选择一项要编辑的记录！', 'error');\r\n");
      out.write("\t\t}\r\n");
      out.write("\t}\r\n");
      out.write("\tfunction detail() {\r\n");
      out.write("\t\tvar rows = datagrid.datagrid('getSelections');\r\n");
      out.write("\t\tif (rows.length == 1) {\r\n");
      out.write("\t\t\t$('#iframeDialog').dialog('setTitle', '【'+rows[0].salebackno+'】销售退货单详情'); \r\n");
      out.write("\t\t\tiframeDialog.dialog('open');\r\n");
      out.write("\t\t\t$(\"#loading\").css(\"display\",\"block\");\r\n");
      out.write("\t\t\tdocument.getElementById(\"iframe\").src = \"saleBackAction!toSaleBackMainDetail.action?salebackno=\"+rows[0].salebackno;\r\n");
      out.write("\t\t} else {\r\n");
      out.write("\t\t\t$.messager.alert('提示', '请选择一项要查看的销售退货单记录！', 'error');\r\n");
      out.write("\t\t}\r\n");
      out.write("\t}\r\n");
      out.write("\tfunction detailSaleBillDetail(salebillno) {\r\n");
      out.write("\t\t$('#iframeDialog').dialog('setTitle', '【'+salebillno+'】销售单详情'); \r\n");
      out.write("\t\t\tiframeDialog.dialog('open');\r\n");
      out.write("\t\t\t$(\"#loading\").css(\"display\",\"block\");\r\n");
      out.write("\t\t\tdocument.getElementById(\"iframe\").src = \"saleAction!toSaleMainDetail.action?salebillno=\"+salebillno;\r\n");
      out.write("\t}\r\n");
      out.write("\tfunction showCdesc(index) {\r\n");
      out.write("\t\tvar rows = datagrid.datagrid('getRows');\r\n");
      out.write("\t\tvar row = rows[index];\r\n");
      out.write("\t\t$.messager.progress({\r\n");
      out.write("\t\t\ttext : '数据加载中....',\r\n");
      out.write("\t\t\tinterval : 100\r\n");
      out.write("\t\t});\r\n");
      out.write("\t\t$.ajax({\r\n");
      out.write("\t\t\turl : 'saleBackAction!showDesc.action',\r\n");
      out.write("\t\t\tdata : {\r\n");
      out.write("\t\t\t\tsalebackno : row.salebackno\r\n");
      out.write("\t\t\t},\r\n");
      out.write("\t\t\tdataType : 'json',\r\n");
      out.write("\t\t\tcache : false,\r\n");
      out.write("\t\t\tsuccess : function(response) {\r\n");
      out.write("\t\t\t\tif (response && response.cdesc) {\r\n");
      out.write("\t\t\t\t\tshowCdescDialog.find('div[name=cdesc]').html(response.cdesc);\r\n");
      out.write("\t\t\t\t\tshowCdescDialog.dialog('open');\r\n");
      out.write("\t\t\t\t} else {\r\n");
      out.write("\t\t\t\t\t$.messager.alert('提示', '没有销售退货单描述！', 'error');\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t\t$.messager.progress('close');\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t});\r\n");
      out.write("\t\tdatagrid.datagrid('unselectAll');\r\n");
      out.write("\t}\r\n");
      out.write("</script>\r\n");
      out.write("</head>\r\n");
      out.write("<body class=\"easyui-layout\">\r\n");
      out.write("    <div region=\"north\" border=\"false\" style=\"height:220px;\">\r\n");
      out.write("\t    <div  id=\"layoutTop\" class=\"easyui-layout\" data-options=\"fit:true\">\r\n");
      out.write("\t        <div region=\"north\"  style=\"height:36px;overflow: hidden;\">\r\n");
      out.write("\t          <form id=\"searchForm\">\r\n");
      out.write("\t\t\t<table class=\"tableForm datagrid-toolbar\" style=\"width: 100%;height:100%;\">\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t<td>销售客户</td>\r\n");
      out.write("\t\t\t\t\t<td>\r\n");
      out.write("\t\t\t\t\t  <select id=\"customerid\" name=\"customerid\" type=\"text\"  class=\"easyui-combobox\" data-options=\"\r\n");
      out.write("\t\t \t\t\t\t\t\t       url:'customerAction!combox.action',\r\n");
      out.write("\t\t\t\t\t\t\t\t      \t valueField:'customerid',\r\n");
      out.write("\t\t\t\t\t\t\t\t         textField:'customername',\r\n");
      out.write("\t\t\t\t\t\t                editable:false\r\n");
      out.write("\t\t \t\t\t\t\t\t       \"  missingMessage=\"请填写销售客户\"  style=\"width: 100px;\">\r\n");
      out.write("\t\t \t\t\t\t\t</select>\r\n");
      out.write("\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t<td>业务员</td>\r\n");
      out.write("\t\t\t\t\t<td>\r\n");
      out.write("\t\t\t\t\t   <select id=\"accountid\" name=\"accountid\" type=\"text\"  class=\"easyui-combobox\" data-options=\"\r\n");
      out.write("\t\t \t\t\t\t\t\t       url:'accounterAction!combox.action',\r\n");
      out.write("\t\t\t\t\t\t\t\t      \t valueField:'accountid',\r\n");
      out.write("\t\t\t\t\t\t\t\t         textField:'accountname',\r\n");
      out.write("\t\t\t\t\t\t                editable:false,\r\n");
      out.write("\t\t\t\t\t\t                onSelect: function(rec){ \r\n");
      out.write("\t\t\t\t\t\t                   $('#salerate').val(rec.rate);\r\n");
      out.write("\t\t\t\t\t\t                }\r\n");
      out.write("\t\t \t\t\t\t\t\t       \"  missingMessage=\"请填写业务员\"  style=\"width: 80px;\">\r\n");
      out.write("\t\t \t\t\t\t\t</select>\r\n");
      out.write("\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t<td>销售操作人</td>\r\n");
      out.write("\t\t\t\t\t<td>\r\n");
      out.write("\t\t\t\t\t   <select id=\"crtuser\" name=\"crtuser\" type=\"text\"  class=\"easyui-combobox\" data-options=\"\r\n");
      out.write("\t\t \t\t\t\t\t\t       url:'userAction!combox.action',\r\n");
      out.write("\t\t\t\t\t\t\t\t      \t valueField:'cid',\r\n");
      out.write("\t\t\t\t\t\t\t\t         textField:'realname',\r\n");
      out.write("\t\t\t\t\t\t                editable:false\r\n");
      out.write("\t\t \t\t\t\t\t\t       \"  missingMessage=\"请填写入库操作人\"  style=\"width: 80px;\">\r\n");
      out.write("\t\t \t\t\t\t\t\t     </select>\r\n");
      out.write("\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t<td>提成比例></td>\r\n");
      out.write("\t\t\t\t\t<td>\r\n");
      out.write("\t\t\t\t\t   <input name=\"salerate\" style=\"width:50px;\" class=\"easyui-numberbox\"/>\r\n");
      out.write("\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t<td>销售日期</td>\r\n");
      out.write("\t\t\t\t\t<td>\r\n");
      out.write("\t\t\t\t\t  <input id=\"begindate\" name=\"ccreatedatetimeStart\" style=\"width:117px;\" class=\"easyui-datetimebox\"/>\r\n");
      out.write("\t\t\t\t\t  <input id=\"enddate\" name=\"ccreatedatetimeEnd\" style=\"width:117px;\" class=\"easyui-datetimebox\"/>\r\n");
      out.write("\t\t\t\t\t  </td>\r\n");
      out.write("\t\t\t    <td><a href=\"javascript:void(0);\" class=\"easyui-linkbutton\" onclick=\"_search();\">过滤</a><a href=\"javascript:void(0);\" class=\"easyui-linkbutton\" onclick=\"cleanSearch();\">取消</a></td>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t</table>\r\n");
      out.write("\t\t</form>\r\n");
      out.write("\t        </div>\r\n");
      out.write("\t        <div region=\"center\">\r\n");
      out.write("\t            <table id=\"datagridSale\"></table>\r\n");
      out.write("\t        </div>\r\n");
      out.write("\t    </div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<div region=\"center\" border=\"false\">\r\n");
      out.write("\t\t<table id=\"datagrid\"></table>\r\n");
      out.write("\t</div>\r\n");
      out.write("\r\n");
      out.write("\t<div id=\"menuTop\" class=\"easyui-menu\" style=\"width:120px;display: none;\">\r\n");
      out.write("\t\t<div onclick=\"add();\" iconCls=\"icon-add\">增加销售退货单</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<div id=\"menuBottom\" class=\"easyui-menu\" style=\"width:120px;display: none;\">\r\n");
      out.write("\t\t<div onclick=\"detail();\" iconCls=\"icon-remove\">查看销售退货</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\r\n");
      out.write("\t<div id=\"showCdescDialog\" style=\"display: none;overflow: auto;width: 500px;height: 400px;\">\r\n");
      out.write("\t\t<div name=\"cdesc\"></div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t\r\n");
      out.write("\t<div id=\"iframeDialog\" style=\"display: none;overflow: hidden;width: 1000px;height: 420px;\">\r\n");
      out.write("\t\t<div id=\"loading\"  style=\"position: absolute;z-index: 10000;\r\n");
      out.write("          top:30;left:0;width:100%;height:95%;background: #DDDDDB  url('");
      out.print(request.getContextPath());
      out.write("/css/images/loading.gif') no-repeat center ;text-align:center;\">\r\n");
      out.write("        </div>\r\n");
      out.write("\t\t<iframe name=\"iframe\" id=\"iframe\" src=\"\"  scrolling=\"auto\" frameborder=\"0\" style=\"width:100%;height:100%;\">\r\n");
      out.write("\t    </iframe>\r\n");
      out.write("\t</div>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
