/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.84
 * Generated at: 2018-03-27 01:58:58 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.com.sys.base;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.util.*;

public final class jeecgGroup_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "/inc.jsp", out, false);
      out.write("\r\n");
      out.write("<script type=\"text/javascript\" charset=\"utf-8\">\r\n");
      out.write("\tvar editRow;\r\n");
      out.write("\tvar editType;/*add or edit or undefined*/\r\n");
      out.write("\tvar treegrid;\r\n");
      out.write("\tvar iconData;\r\n");
      out.write("\t$(function() {\r\n");
      out.write("\r\n");
      out.write("\t\ticonData = [ {\r\n");
      out.write("\t\t\tvalue : '',\r\n");
      out.write("\t\t\ttext : '默认'\r\n");
      out.write("\t\t}, \r\n");
      out.write("\t\t{value : 'icon-annex', text : 'icon-annex'},\r\n");
      out.write("\t\t{value : 'icon-bars', text : 'icon-bars'},\r\n");
      out.write("\t\t{value : 'icon-bing', text : 'icon-bing'},\r\n");
      out.write("\t\t{value : 'icon-blue', text : 'icon-blue'},\r\n");
      out.write("\t\t{value : 'icon-casa', text : 'icon-casa'},\r\n");
      out.write("\t\t{value : 'icon-calc', text : 'icon-calc'},\r\n");
      out.write("\t\t{value : 'icon-cale', text : 'icon-cale'},\r\n");
      out.write("\t\t{value : 'icon-conf', text : 'icon-conf'},\r\n");
      out.write("\t\t{value : 'icon-danr', text : 'icon-danr'},\r\n");
      out.write("\t\t{value : 'icon-ding', text : 'icon-ding'},\r\n");
      out.write("\t\t{value : 'icon-ding', text : 'icon-ding'},\r\n");
      out.write("\t\t{value : 'icon-doll', text : 'icon-doll'},\r\n");
      out.write("\t\t{value : 'icon-duot', text : 'icon-duot'},\r\n");
      out.write("\t\t{value : 'icon-eart', text : 'icon-eart'},\r\n");
      out.write("\t\t{value : 'icon-face', text : 'icon-face'},\r\n");
      out.write("\t\t{value : 'icon-find', text : 'icon-find'},\r\n");
      out.write("\t\t{value : 'icon-gold', text : 'icon-gold'},\r\n");
      out.write("\t\t{value : 'icon-gole', text : 'icon-gole'},\r\n");
      out.write("\t\t{value : 'icon-gree', text : 'icon-gree'},\r\n");
      out.write("\t\t{value : 'icon-grou', text : 'icon-grou'},\r\n");
      out.write("\t\t{value : 'icon-hard', text : 'icon-hard'},\r\n");
      out.write("\t\t{value : 'icon-hihi', text : 'icon-hihi'},\r\n");
      out.write("\t\t{value : 'icon-hibo', text : 'icon-hibo'},\r\n");
      out.write("\t\t{value : 'icon-hoho', text : 'icon-hoho'},\r\n");
      out.write("\t\t{value : 'icon-home', text : 'icon-home'},\r\n");
      out.write("\t\t{value : 'icon-hote', text : 'icon-hote'},\r\n");
      out.write("\t\t{value : 'icon-inpu', text : 'icon-inpu'},\r\n");
      out.write("\t\t{value : 'icon-keys', text : 'icon-keys'},\r\n");
      out.write("\t\t{value : 'icon-limi', text : 'icon-limi'},\r\n");
      out.write("\t\t{value : 'icon-lock', text : 'icon-lock'},\r\n");
      out.write("\t\t{value : 'icon-love', text : 'icon-love'},\r\n");
      out.write("\t\t{value : 'icon-mans', text : 'icon-mans'},\r\n");
      out.write("\t\t{value : 'icon-mous', text : 'icon-mous'},\r\n");
      out.write("\t\t{value : 'icon-newd', text : 'icon-newd'},\r\n");
      out.write("\t\t{value : 'icon-offe', text : 'icon-offe'},\r\n");
      out.write("\t\t{value : 'icon-orde', text : 'icon-orde'},\r\n");
      out.write("\t\t{value : 'icon-pass', text : 'icon-pass'},\r\n");
      out.write("\t\t{value : 'icon-pens', text : 'icon-pens'},\r\n");
      out.write("\t\t{value : 'icon-penc', text : 'icon-penc'},\r\n");
      out.write("\t\t{value : 'icon-prin', text : 'icon-prin'},\r\n");
      out.write("\t\t{value : 'icon-quxi', text : 'icon-quxi'},\r\n");
      out.write("\t\t{value : 'icon-relo', text : 'icon-relo'},\r\n");
      out.write("\t\t{value : 'icon-rmbs', text : 'icon-rmbs'},\r\n");
      out.write("\t\t{value : 'icon-road', text : 'icon-road'},\r\n");
      out.write("\t\t{value : 'icon-sand', text : 'icon-sand'},\r\n");
      out.write("\t\t{value : 'icon-seal', text : 'icon-seal'},\r\n");
      out.write("\t\t{value : 'icon-seal', text : 'icon-seal'},\r\n");
      out.write("\t\t{value : 'icon-shee', text : 'icon-shee'},\r\n");
      out.write("\t\t{value : 'icon-spec', text : 'icon-spec'},\r\n");
      out.write("\t\t{value : 'icon-star', text : 'icon-star'},\r\n");
      out.write("\t\t{value : 'icon-stgo', text : 'icon-stgo'},\r\n");
      out.write("\t\t{value : 'icon-talk', text : 'icon-talk'},\r\n");
      out.write("\t\t{value : 'icon-task', text : 'icon-task'},\r\n");
      out.write("\t\t{value : 'icon-user', text : 'icon-user'},\r\n");
      out.write("\t\t{value : 'icon-yiyi', text : 'icon-yiyi'},\r\n");
      out.write("\t\t{value : 'icon-yuan', text : 'icon-yuan'},\r\n");
      out.write("\t\t{value : 'icon-zhen', text : 'icon-zhen'},\r\n");
      out.write("\t\t{value : 'icon-zhus', text : 'icon-zhus'},\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t{\r\n");
      out.write("\t\t\tvalue : 'icon-add',\r\n");
      out.write("\t\t\ttext : 'icon-add'\r\n");
      out.write("\t\t}, {\r\n");
      out.write("\t\t\tvalue : 'icon-edit',\r\n");
      out.write("\t\t\ttext : 'icon-edit'\r\n");
      out.write("\t\t}, {\r\n");
      out.write("\t\t\tvalue : 'icon-remove',\r\n");
      out.write("\t\t\ttext : 'icon-remove'\r\n");
      out.write("\t\t}, {\r\n");
      out.write("\t\t\tvalue : 'icon-save',\r\n");
      out.write("\t\t\ttext : 'icon-save'\r\n");
      out.write("\t\t}, {\r\n");
      out.write("\t\t\tvalue : 'icon-cut',\r\n");
      out.write("\t\t\ttext : 'icon-cut'\r\n");
      out.write("\t\t}, {\r\n");
      out.write("\t\t\tvalue : 'icon-ok',\r\n");
      out.write("\t\t\ttext : 'icon-ok'\r\n");
      out.write("\t\t}, {\r\n");
      out.write("\t\t\tvalue : 'icon-no',\r\n");
      out.write("\t\t\ttext : 'icon-no'\r\n");
      out.write("\t\t}, {\r\n");
      out.write("\t\t\tvalue : 'icon-cancel',\r\n");
      out.write("\t\t\ttext : 'icon-cancel'\r\n");
      out.write("\t\t}, {\r\n");
      out.write("\t\t\tvalue : 'icon-reload',\r\n");
      out.write("\t\t\ttext : 'icon-reload'\r\n");
      out.write("\t\t}, {\r\n");
      out.write("\t\t\tvalue : 'icon-search',\r\n");
      out.write("\t\t\ttext : 'icon-search'\r\n");
      out.write("\t\t}, {\r\n");
      out.write("\t\t\tvalue : 'icon-print',\r\n");
      out.write("\t\t\ttext : 'icon-print'\r\n");
      out.write("\t\t}, {\r\n");
      out.write("\t\t\tvalue : 'icon-help',\r\n");
      out.write("\t\t\ttext : 'icon-help'\r\n");
      out.write("\t\t}, {\r\n");
      out.write("\t\t\tvalue : 'icon-undo',\r\n");
      out.write("\t\t\ttext : 'icon-undo'\r\n");
      out.write("\t\t}, {\r\n");
      out.write("\t\t\tvalue : 'icon-redo',\r\n");
      out.write("\t\t\ttext : 'icon-redo'\r\n");
      out.write("\t\t}, {\r\n");
      out.write("\t\t\tvalue : 'icon-back',\r\n");
      out.write("\t\t\ttext : 'icon-back'\r\n");
      out.write("\t\t}, {\r\n");
      out.write("\t\t\tvalue : 'icon-sum',\r\n");
      out.write("\t\t\ttext : 'icon-sum'\r\n");
      out.write("\t\t}, {\r\n");
      out.write("\t\t\tvalue : 'icon-tip',\r\n");
      out.write("\t\t\ttext : 'icon-tip'\r\n");
      out.write("\t\t} ];\r\n");
      out.write("\r\n");
      out.write("\t\ttreegrid = $('#treegrid').treegrid({\r\n");
      out.write("\t\t\turl : 'jeecgGroupAction!treegrid.action',\r\n");
      out.write("\t\t\ttoolbar : [ {\r\n");
      out.write("\t\t\t\ttext : '展开',\r\n");
      out.write("\t\t\t\ticonCls : 'icon-redo',\r\n");
      out.write("\t\t\t\thandler : function() {\r\n");
      out.write("\t\t\t\t\tvar node = treegrid.treegrid('getSelected');\r\n");
      out.write("\t\t\t\t\tif (node) {\r\n");
      out.write("\t\t\t\t\t\ttreegrid.treegrid('expandAll', node.obid);\r\n");
      out.write("\t\t\t\t\t} else {\r\n");
      out.write("\t\t\t\t\t\ttreegrid.treegrid('expandAll');\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t}, '-', {\r\n");
      out.write("\t\t\t\ttext : '折叠',\r\n");
      out.write("\t\t\t\ticonCls : 'icon-undo',\r\n");
      out.write("\t\t\t\thandler : function() {\r\n");
      out.write("\t\t\t\t\tvar node = treegrid.treegrid('getSelected');\r\n");
      out.write("\t\t\t\t\tif (node) {\r\n");
      out.write("\t\t\t\t\t\ttreegrid.treegrid('collapseAll', node.obid);\r\n");
      out.write("\t\t\t\t\t} else {\r\n");
      out.write("\t\t\t\t\t\ttreegrid.treegrid('collapseAll');\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t}, '-', {\r\n");
      out.write("\t\t\t\ttext : '刷新',\r\n");
      out.write("\t\t\t\ticonCls : 'icon-reload',\r\n");
      out.write("\t\t\t\thandler : function() {\r\n");
      out.write("\t\t\t\t\teditRow = undefined;\r\n");
      out.write("\t\t\t\t\teditType = undefined;\r\n");
      out.write("\t\t\t\t\ttreegrid.treegrid('reload');\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t}, '-', {\r\n");
      out.write("\t\t\t\ttext : '增加',\r\n");
      out.write("\t\t\t\ticonCls : 'icon-add',\r\n");
      out.write("\t\t\t\thandler : function() {\r\n");
      out.write("\t\t\t\t\tappend();\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t}, '-', {\r\n");
      out.write("\t\t\t\ttext : '删除',\r\n");
      out.write("\t\t\t\ticonCls : 'icon-remove',\r\n");
      out.write("\t\t\t\thandler : function() {\r\n");
      out.write("\t\t\t\t\tremove();\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t}, '-', {\r\n");
      out.write("\t\t\t\ttext : '编辑',\r\n");
      out.write("\t\t\t\ticonCls : 'icon-edit',\r\n");
      out.write("\t\t\t\thandler : function() {\r\n");
      out.write("\t\t\t\t\tedit();\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t}, '-', {\r\n");
      out.write("\t\t\t\ttext : '保存',\r\n");
      out.write("\t\t\t\ticonCls : 'icon-save',\r\n");
      out.write("\t\t\t\thandler : function() {\r\n");
      out.write("\t\t\t\t\tif (editRow != undefined) {\r\n");
      out.write("\t\t\t\t\t\ttreegrid.treegrid('endEdit', editRow.obid);\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t}, '-', {\r\n");
      out.write("\t\t\t\ttext : '取消编辑',\r\n");
      out.write("\t\t\t\ticonCls : 'icon-undo',\r\n");
      out.write("\t\t\t\thandler : function() {\r\n");
      out.write("\t\t\t\t\tif (editRow) {\r\n");
      out.write("\t\t\t\t\t\ttreegrid.treegrid('cancelEdit', editRow.obid);\r\n");
      out.write("\t\t\t\t\t\tvar p = treegrid.treegrid('getParent', editRow.obid);\r\n");
      out.write("\t\t\t\t\t\tif (p) {\r\n");
      out.write("\t\t\t\t\t\t\ttreegrid.treegrid('reload', p.obid);\r\n");
      out.write("\t\t\t\t\t\t} else {\r\n");
      out.write("\t\t\t\t\t\t\ttreegrid.treegrid('reload');\r\n");
      out.write("\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t\teditRow = undefined;\r\n");
      out.write("\t\t\t\t\t\teditType = undefined;\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t}, '-', {\r\n");
      out.write("\t\t\t\ttext : '取消选中',\r\n");
      out.write("\t\t\t\ticonCls : 'icon-undo',\r\n");
      out.write("\t\t\t\thandler : function() {\r\n");
      out.write("\t\t\t\t\ttreegrid.treegrid('unselectAll');\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t}, '-' ],\r\n");
      out.write("\t\t\ttitle : '',\r\n");
      out.write("\t\t\ticonCls : 'icon-save',\r\n");
      out.write("\t\t\tfit : true,\r\n");
      out.write("\t\t\tfitColumns : false,\r\n");
      out.write("\t\t\tnowrap : true,\r\n");
      out.write("\t\t\tanimate : false,\r\n");
      out.write("\t\t\tborder : false,\r\n");
      out.write("\t\t\tidField : 'obid',\r\n");
      out.write("\t\t\ttreeField : 'cname',\r\n");
      out.write("\t\t\tfrozenColumns : [ [ {\r\n");
      out.write("\t\t\t\ttitle : '机构编码',\r\n");
      out.write("\t\t\t\tfield : 'obid',\r\n");
      out.write("\t\t\t\twidth : 150,\r\n");
      out.write("\t\t\t\thidden : false\r\n");
      out.write("\t\t\t}, {\r\n");
      out.write("\t\t\t\tfield : 'cname',\r\n");
      out.write("\t\t\t\ttitle : '组织机构',\r\n");
      out.write("\t\t\t\twidth : 180,\r\n");
      out.write("\t\t\t\teditor : {\r\n");
      out.write("\t\t\t\t\ttype : 'validatebox',\r\n");
      out.write("\t\t\t\t\toptions : {\r\n");
      out.write("\t\t\t\t\t\trequired : true\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t},\r\n");
      out.write("\t\t\t\tformatter : function(value) {\r\n");
      out.write("\t\t\t\t\tif (value) {\r\n");
      out.write("\t\t\t\t\t\treturn sy.fs('<span title=\"{0}\">{1}</span>', value, value);\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t} ] ],\r\n");
      out.write("\t\t\tcolumns : [ [ \r\n");
      out.write("\t\t\t{\r\n");
      out.write("\t\t\t\tfield : 'cpid',\r\n");
      out.write("\t\t\t\ttitle : '上级',\r\n");
      out.write("\t\t\t\twidth : 150,\r\n");
      out.write("\t\t\t\tformatter : function(value, rowData, rowIndex) {\r\n");
      out.write("\t\t\t\t\treturn rowData.cpname;\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t}, {\r\n");
      out.write("\t\t\t\tfield : 'cpname',\r\n");
      out.write("\t\t\t\ttitle : '上级',\r\n");
      out.write("\t\t\t\twidth : 150,\r\n");
      out.write("\t\t\t\thidden : true\r\n");
      out.write("\t\t\t} ] ],\r\n");
      out.write("\t\t\tonDblClickRow : function(row) {\r\n");
      out.write("\t\t\t\tif (editRow != undefined) {\r\n");
      out.write("\t\t\t\t\ttreegrid.treegrid('endEdit', editRow.obid);\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\r\n");
      out.write("\t\t\t\tif (editRow == undefined) {\r\n");
      out.write("\t\t\t\t\ttreegrid.treegrid('beginEdit', row.obid);\r\n");
      out.write("\t\t\t\t\teditRow = row;\r\n");
      out.write("\t\t\t\t\teditType = 'edit';\r\n");
      out.write("\t\t\t\t\ttreegrid.treegrid('unselectAll');\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t},\r\n");
      out.write("\t\t\tonAfterEdit : function(row, changes) {\r\n");
      out.write("\t\t\t\tif (editType == undefined) {\r\n");
      out.write("\t\t\t\t\teditRow = undefined;\r\n");
      out.write("\t\t\t\t\ttreegrid.treegrid('unselectAll');\r\n");
      out.write("\t\t\t\t\treturn;\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\r\n");
      out.write("\t\t\t\tvar url = '';\r\n");
      out.write("\t\t\t\tif (editType == 'add') {\r\n");
      out.write("\t\t\t\t\turl = 'jeecgGroupAction!add.action';\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t\tif (editType == 'edit') {\r\n");
      out.write("\t\t\t\t\turl = 'jeecgGroupAction!edit.action';\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t$.ajax({\r\n");
      out.write("\t\t\t\t\turl : url,\r\n");
      out.write("\t\t\t\t\tdata : row,\r\n");
      out.write("\t\t\t\t\tdataType : 'json',\r\n");
      out.write("\t\t\t\t\tsuccess : function(r) {\r\n");
      out.write("\t\t\t\t\t\tif (r.success) {\r\n");
      out.write("\t\t\t\t\t\t\ttreegrid.treegrid('reload');\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t$.messager.show({\r\n");
      out.write("\t\t\t\t\t\t\t\tmsg : r.msg,\r\n");
      out.write("\t\t\t\t\t\t\t\ttitle : '成功'\r\n");
      out.write("\t\t\t\t\t\t\t});\r\n");
      out.write("\t\t\t\t\t\t\teditRow = undefined;\r\n");
      out.write("\t\t\t\t\t\t\teditType = undefined;\r\n");
      out.write("\t\t\t\t\t\t} else {\r\n");
      out.write("\t\t\t\t\t\t\t/*datagrid.datagrid('rejectChanges');*/\r\n");
      out.write("\t\t\t\t\t\t\ttreegrid.treegrid('beginEdit', editRow.obid);\r\n");
      out.write("\t\t\t\t\t\t\t$.messager.alert('错误', r.msg, 'error');\r\n");
      out.write("\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t\ttreegrid.treegrid('unselectAll');\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t});\r\n");
      out.write("\r\n");
      out.write("\t\t\t},\r\n");
      out.write("\t\t\tonContextMenu : function(e, row) {\r\n");
      out.write("\t\t\t\te.preventDefault();\r\n");
      out.write("\t\t\t\t$(this).treegrid('unselectAll');\r\n");
      out.write("\t\t\t\t$(this).treegrid('select', row.obid);\r\n");
      out.write("\t\t\t\t$('#menu').menu('show', {\r\n");
      out.write("\t\t\t\t\tleft : e.pageX,\r\n");
      out.write("\t\t\t\t\ttop : e.pageY\r\n");
      out.write("\t\t\t\t});\r\n");
      out.write("\t\t\t},\r\n");
      out.write("\t\t\tonLoadSuccess : function(row, data) {\r\n");
      out.write("\t\t\t\t/*var t = $(this);\r\n");
      out.write("\t\t\t\tif (data) {\r\n");
      out.write("\t\t\t\t\t$(data).each(function(index, d) {\r\n");
      out.write("\t\t\t\t\t\tif (this.state == 'closed') {\r\n");
      out.write("\t\t\t\t\t\t\tt.treegrid('expandAll');\r\n");
      out.write("\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t});\r\n");
      out.write("\t\t\t\t}*/\r\n");
      out.write("\t\t\t},\r\n");
      out.write("\t\t\tonExpand : function(row) {\r\n");
      out.write("\t\t\t\ttreegrid.treegrid('unselectAll');\r\n");
      out.write("\t\t\t},\r\n");
      out.write("\t\t\tonCollapse : function(row) {\r\n");
      out.write("\t\t\t\ttreegrid.treegrid('unselectAll');\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t});\r\n");
      out.write("\r\n");
      out.write("\t});\r\n");
      out.write("\r\n");
      out.write("\tfunction edit() {\r\n");
      out.write("\t\tvar node = treegrid.treegrid('getSelected');\r\n");
      out.write("\t\tif (node && node.obid) {\r\n");
      out.write("\t\t\tif (editRow != undefined) {\r\n");
      out.write("\t\t\t\ttreegrid.treegrid('endEdit', editRow.obid);\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\r\n");
      out.write("\t\t\tif (editRow == undefined) {\r\n");
      out.write("\t\t\t\ttreegrid.treegrid('beginEdit', node.obid);\r\n");
      out.write("\t\t\t\teditRow = node;\r\n");
      out.write("\t\t\t\teditType = 'edit';\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t} else {\r\n");
      out.write("\t\t\t$.messager.show({\r\n");
      out.write("\t\t\t\tmsg : '请选择一项进行修改！',\r\n");
      out.write("\t\t\t\ttitle : '错误'\r\n");
      out.write("\t\t\t});\r\n");
      out.write("\t\t}\r\n");
      out.write("\t}\r\n");
      out.write("\tfunction append() {\r\n");
      out.write("\t\tif (editRow != undefined) {\r\n");
      out.write("\t\t\ttreegrid.treegrid('endEdit', editRow.obid);\r\n");
      out.write("\t\t}\r\n");
      out.write("\r\n");
      out.write("\t\tif (editRow == undefined) {\r\n");
      out.write("\t\t\tvar node = treegrid.treegrid('getSelected');\r\n");
      out.write("\t\t\tvar row = [ {\r\n");
      out.write("\t\t\t\tobid : '',\r\n");
      out.write("\t\t\t\tcname : '组织机构',\r\n");
      out.write("\t\t\t\tcurl : '',\r\n");
      out.write("\t\t\t\tcpid : node == null ? '' : node.obid\r\n");
      out.write("\t\t\t} ];\r\n");
      out.write("\t\t\ttreegrid.treegrid('append', {\r\n");
      out.write("\t\t\t\tparent : node == null ? '' : node.obid,\r\n");
      out.write("\t\t\t\tdata : row\r\n");
      out.write("\t\t\t});\r\n");
      out.write("\r\n");
      out.write("\t\t\teditRow = row[0];\r\n");
      out.write("\t\t\teditType = 'add';\r\n");
      out.write("\t\t\ttreegrid.treegrid('select', editRow.obid);\r\n");
      out.write("\t\t\ttreegrid.treegrid('beginEdit', editRow.obid);\r\n");
      out.write("\t\t}\r\n");
      out.write("\t}\r\n");
      out.write("\tfunction remove() {\r\n");
      out.write("\t\tvar node = treegrid.treegrid('getSelected');\r\n");
      out.write("\t\tif (node) {\r\n");
      out.write("\t\t\t$.messager.confirm('询问', '您确定要删除【' + node.cname + '】？', function(b) {\r\n");
      out.write("\t\t\t\tif (b) {\r\n");
      out.write("\t\t\t\t\t$.ajax({\r\n");
      out.write("\t\t\t\t\t\turl : 'jeecgGroupAction!delete.action',\r\n");
      out.write("\t\t\t\t\t\tdata : {\r\n");
      out.write("\t\t\t\t\t\t\tobid : node.obid\r\n");
      out.write("\t\t\t\t\t\t},\r\n");
      out.write("\t\t\t\t\t\tcache : false,\r\n");
      out.write("\t\t\t\t\t\tdataType : \"json\",\r\n");
      out.write("\t\t\t\t\t\tsuccess : function(r) {\r\n");
      out.write("\t\t\t\t\t\t\tif (r.success) {\r\n");
      out.write("\t\t\t\t\t\t\t\ttreegrid.treegrid('remove', r.obj);\r\n");
      out.write("\t\t\t\t\t\t\t\t$.messager.show({\r\n");
      out.write("\t\t\t\t\t\t\t\t\tmsg : r.msg,\r\n");
      out.write("\t\t\t\t\t\t\t\t\ttitle : '提示'\r\n");
      out.write("\t\t\t\t\t\t\t\t});\r\n");
      out.write("\t\t\t\t\t\t\t\teditRow = undefined;\r\n");
      out.write("\t\t\t\t\t\t\t} else {\r\n");
      out.write("\t\t\t\t\t\t\t\t$.messager.show({\r\n");
      out.write("\t\t\t\t\t\t\t\t\tmsg : '删除失败!',\r\n");
      out.write("\t\t\t\t\t\t\t\t\ttitle : '提示'\r\n");
      out.write("\t\t\t\t\t\t\t\t});\r\n");
      out.write("\t\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t});\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t});\r\n");
      out.write("\t\t}\r\n");
      out.write("\t}\r\n");
      out.write("</script>\r\n");
      out.write("</head>\r\n");
      out.write("<body class=\"easyui-layout\" fit=\"true\">\r\n");
      out.write("\t<div region=\"center\" border=\"false\" style=\"overflow: hidden;\">\r\n");
      out.write("\t\t<table id=\"treegrid\"></table>\r\n");
      out.write("\t</div>\r\n");
      out.write("\r\n");
      out.write("\t<div id=\"menu\" class=\"easyui-menu\" style=\"width:120px;display: none;\">\r\n");
      out.write("\t\t<div onclick=\"append();\" iconCls=\"icon-add\">增加</div>\r\n");
      out.write("\t\t<div onclick=\"remove();\" iconCls=\"icon-remove\">删除</div>\r\n");
      out.write("\t\t<div onclick=\"edit();\" iconCls=\"icon-edit\">编辑</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
