/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.84
 * Generated at: 2018-03-27 01:58:57 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.com.sys.base;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.util.*;

public final class note_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "/inc.jsp", out, false);
      out.write("\r\n");
      out.write("<script type=\"text/javascript\" charset=\"utf-8\">\r\n");
      out.write("    var searchForm;\r\n");
      out.write("\tvar datagrid;\r\n");
      out.write("\tvar showCdescDialog;\r\n");
      out.write("\t//update-begin author:anchao for:防止form重复提交  date：20130310\r\n");
      out.write("\tvar formFlag = true;\r\n");
      out.write("\t//update-end author:anchao for:防止form重复提交  date：20130310\r\n");
      out.write("\t$(function() {\r\n");
      out.write("\t    //查询列表\t\r\n");
      out.write("\t    searchForm = $('#searchForm').form();\r\n");
      out.write("\t\tdatagrid = $('#datagrid').datagrid({\r\n");
      out.write("\t\t\turl : 'noteAction!datagrid.action',\r\n");
      out.write("\t\t\ttitle : '公告管理列表',\r\n");
      out.write("\t\t\ticonCls : 'icon-save',\r\n");
      out.write("\t\t\tpagination : true,\r\n");
      out.write("\t\t\tpagePosition : 'bottom',\r\n");
      out.write("\t\t\trownumbers : true,\r\n");
      out.write("\t\t\tpageSize : 10,\r\n");
      out.write("\t\t\tpageList : [ 10, 20, 30, 40 ],\r\n");
      out.write("\t\t\tfit : true,\r\n");
      out.write("\t\t\tfitColumns : true,\r\n");
      out.write("\t\t\tnowrap : true,\r\n");
      out.write("\t\t\tborder : false,\r\n");
      out.write("\t\t\tidField : 'obid',\r\n");
      out.write("\t\t\tsortName : 'createDt',\r\n");
      out.write("\t\t\tsortOrder : 'desc',\r\n");
      out.write("\t\t\tcolumns : [ [ \r\n");
      out.write("\t\t\t{field:'ck',checkbox:true,\r\n");
      out.write("\t\t\t\t\t\tformatter:function(value,row,index){\r\n");
      out.write("\t\t\t\t\t\t\treturn row.obid;\r\n");
      out.write("\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t},\r\n");
      out.write("\t\t\t   {field:'title',title:'标题',align:'center',sortable:true,\r\n");
      out.write("\t\t\t\t\tformatter:function(value,row,index){\r\n");
      out.write("\t\t\t\t\t\treturn row.title;\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t},\t\t\t\t\r\n");
      out.write("\t\t\t   {field:'content',title:'内容',align:'center',sortable:true,\r\n");
      out.write("\t\t\t\t\tformatter:function(value,row,index){\r\n");
      out.write("\t\t\t\t\t\treturn '<span class=\"icon-search\" style=\"display:inline-block;vertical-align:middle;width:16px;height:16px;\"></span><a href=\"javascript:void(0);\" onclick=\"showCdesc(' + index + ');\">查看详细</a>';\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t}\t\t\t\t\r\n");
      out.write("\t\t\t ] ],\r\n");
      out.write("\t\t\ttoolbar : [ {\r\n");
      out.write("\t\t\t\ttext : '增加',\r\n");
      out.write("\t\t\t\ticonCls : 'icon-add',\r\n");
      out.write("\t\t\t\thandler : function() {\r\n");
      out.write("\t\t\t\t\tadd();\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t}, '-', {\r\n");
      out.write("\t\t\t\ttext : '删除',\r\n");
      out.write("\t\t\t\ticonCls : 'icon-remove',\r\n");
      out.write("\t\t\t\thandler : function() {\r\n");
      out.write("\t\t\t\t\tdel();\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t}, '-', {\r\n");
      out.write("\t\t\t\ttext : '修改',\r\n");
      out.write("\t\t\t\ticonCls : 'icon-edit',\r\n");
      out.write("\t\t\t\thandler : function() {\r\n");
      out.write("\t\t\t\t\tedit();\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t}, '-', {\r\n");
      out.write("\t\t\t\ttext : '取消选中',\r\n");
      out.write("\t\t\t\ticonCls : 'icon-undo',\r\n");
      out.write("\t\t\t\thandler : function() {\r\n");
      out.write("\t\t\t\t\tdatagrid.datagrid('unselectAll');\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t}, '-' ],\r\n");
      out.write("\t\t\tonRowContextMenu : function(e, rowIndex, rowData) {\r\n");
      out.write("\t\t\t\te.preventDefault();\r\n");
      out.write("\t\t\t\t$(this).datagrid('unselectAll');\r\n");
      out.write("\t\t\t\t$(this).datagrid('selectRow', rowIndex);\r\n");
      out.write("\t\t\t\t$('#menu').menu('show', {\r\n");
      out.write("\t\t\t\t\tleft : e.pageX,\r\n");
      out.write("\t\t\t\t\ttop : e.pageY\r\n");
      out.write("\t\t\t\t});\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t});\r\n");
      out.write("\r\n");
      out.write("\t\tshowCdescDialog = $('#showCdescDialog').show().dialog({\r\n");
      out.write("\t\t\ttitle : '公告管理描述',\r\n");
      out.write("\t\t\tmodal : true,\r\n");
      out.write("\t\t\tclosed : true,\r\n");
      out.write("\t\t\tmaximizable : true\r\n");
      out.write("\t\t});\r\n");
      out.write("\r\n");
      out.write("\t});\r\n");
      out.write("\r\n");
      out.write("\tfunction _search() {\r\n");
      out.write("\t\tdatagrid.datagrid('load', sy.serializeObject(searchForm));\r\n");
      out.write("\t}\r\n");
      out.write("\tfunction cleanSearch() {\r\n");
      out.write("\t\tdatagrid.datagrid('load', {});\r\n");
      out.write("\t\tsearchForm.find('input').val('');\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\t//update-begin author:gaoxingang for:优化将添加和修改页面分开  date：20130309\r\n");
      out.write("\tfunction add() {\r\n");
      out.write("\t\tdatagrid.datagrid('uncheckAll').datagrid('unselectAll').datagrid('clearSelections');\r\n");
      out.write("\t\t$('<div/>').dialog({     \r\n");
      out.write("\t\t\thref : '");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/com/sys/base/note-add.jsp',\r\n");
      out.write("\t\t\twidth : 500,\r\n");
      out.write("\t\t\theight : 400,\r\n");
      out.write("\t\t\tmodal : true,\r\n");
      out.write("\t\t\ttitle : '添加公告管理',\r\n");
      out.write("\t\t\tbuttons : [ {\r\n");
      out.write("\t\t\t\ttext : '增加',\r\n");
      out.write("\t\t\t\ticonCls : 'icon-add',\r\n");
      out.write("\t\t\t\thandler : function() {\r\n");
      out.write("\t\t\t\t\tvar d = $(this).closest('.window-body');\r\n");
      out.write("\t\t\t\t\t$('#noteAddForm').form({\r\n");
      out.write("\t\t\t\t\t\turl : '");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/noteAction!add.action',\r\n");
      out.write("\t\t\t\t\t\tsuccess : function(result) {\r\n");
      out.write("\t\t\t\t\t\t\ttry {\r\n");
      out.write("\t\t\t\t\t\t\t\tvar r = $.parseJSON(result);\r\n");
      out.write("\t\t\t\t\t\t\t\tif (r.success) {\r\n");
      out.write("\t\t\t\t\t\t\t\t\tdatagrid.datagrid('reload');\r\n");
      out.write("\t\t\t\t\t\t\t\t\td.dialog('destroy');\r\n");
      out.write("\t\t\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t\t\t\t$.messager.show({\r\n");
      out.write("\t\t\t\t\t\t\t\t\ttitle : '提示',\r\n");
      out.write("\t\t\t\t\t\t\t\t\tmsg : r.msg\r\n");
      out.write("\t\t\t\t\t\t\t\t});\r\n");
      out.write("\t\t\t\t\t\t\t} catch (e) {\r\n");
      out.write("\t\t\t\t\t\t\t\t$.messager.alert('提示', result);\r\n");
      out.write("\t\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t\t\t//update-begin author:anchao for:防止form重复提交  date：20130310\r\n");
      out.write("\t\t\t\t\t\t\tformFlag =  true;\r\n");
      out.write("\t\t\t\t\t\t\t//update-end author:anchao for:防止form重复提交  date：20130310\r\n");
      out.write("\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t});\r\n");
      out.write("\t\t\t\t\t//update-begin author:anchao for:防止form重复提交  date：20130310\r\n");
      out.write("\t\t\t\t\tif(formFlag){\r\n");
      out.write("\t\t\t\t\t\tformFlag =  false;\r\n");
      out.write("\t\t\t\t\t//update-end author:anchao for:防止form重复提交  date：20130310\r\n");
      out.write("\t\t\t\t\t\t$('#noteAddForm').submit();\r\n");
      out.write("\t\t\t\t\t//update-begin author:anchao for:防止form重复提交  date：20130310\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t//update-end author:anchao for:防止form重复提交  date：20130310\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t} ],\r\n");
      out.write("\t\t\tonClose : function() {\r\n");
      out.write("\t\t\t\t$(this).dialog('destroy');\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t});\r\n");
      out.write("\t}\r\n");
      out.write("\t//update-end author:gaoxingang for:优化将添加和修改页面分开  date：20130309\r\n");
      out.write("\t\r\n");
      out.write("\tfunction del() {\r\n");
      out.write("\t\tvar rows = datagrid.datagrid('getSelections');\r\n");
      out.write("\t\tvar ids = [];\r\n");
      out.write("\t\tif (rows.length > 0) {\r\n");
      out.write("\t\t\t$.messager.confirm('请确认', '您要删除当前所选项目？', function(r) {\r\n");
      out.write("\t\t\t\tif (r) {\r\n");
      out.write("\t\t\t\t\tfor ( var i = 0; i < rows.length; i++) {\r\n");
      out.write("\t\t\t\t\t\tids.push(rows[i].obid);\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t$.ajax({\r\n");
      out.write("\t\t\t\t\t\turl : 'noteAction!delete.action',\r\n");
      out.write("\t\t\t\t\t\tdata : {\r\n");
      out.write("\t\t\t\t\t\t\tids : ids.join(',')\r\n");
      out.write("\t\t\t\t\t\t},\r\n");
      out.write("\t\t\t\t\t\tdataType : 'json',\r\n");
      out.write("\t\t\t\t\t\tsuccess : function(response) {\r\n");
      out.write("\t\t\t\t\t\t\tdatagrid.datagrid('load');\r\n");
      out.write("\t\t\t\t\t\t\tdatagrid.datagrid('unselectAll');\r\n");
      out.write("\t\t\t\t\t\t\t$.messager.show({\r\n");
      out.write("\t\t\t\t\t\t\t\ttitle : '提示',\r\n");
      out.write("\t\t\t\t\t\t\t\tmsg : '删除成功！'\r\n");
      out.write("\t\t\t\t\t\t\t});\r\n");
      out.write("\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t});\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t});\r\n");
      out.write("\t\t} else {\r\n");
      out.write("\t\t\t$.messager.alert('提示', '请选择要删除的记录！', 'error');\r\n");
      out.write("\t\t}\r\n");
      out.write("\t}\r\n");
      out.write("\t//update-begin author:gaoxingang for:优化将添加和修改页面分开  date：20130309\r\n");
      out.write("\tfunction edit() {\r\n");
      out.write("\t\tvar rows = datagrid.datagrid('getSelections');\r\n");
      out.write("\t\tif (rows.length == 1) {\r\n");
      out.write("\t\t\t$('<div/>').dialog({\r\n");
      out.write("\t\t\t\thref : '");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/noteAction!toEdit.action?obid=' + rows[0].obid,\r\n");
      out.write("\t\t\t\twidth : 500,\r\n");
      out.write("\t\t\t\theight : 400,\r\n");
      out.write("\t\t\t\tmodal : true,\r\n");
      out.write("\t\t\t\ttitle : '编辑公告管理',\r\n");
      out.write("\t\t\t\tbuttons : [ {\r\n");
      out.write("\t\t\t\t\ttext : '编辑',\r\n");
      out.write("\t\t\t\t\ticonCls : 'icon-edit',\r\n");
      out.write("\t\t\t\t\thandler : function() {\r\n");
      out.write("\t\t\t\t\t\tvar d = $(this).closest('.window-body');\r\n");
      out.write("\t\t\t\t\t\t$('#noteEditForm').form({\r\n");
      out.write("\t\t\t\t\t\t\turl : '");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/noteAction!edit.action',\r\n");
      out.write("\t\t\t\t\t\t\tsuccess : function(result) {\r\n");
      out.write("\t\t\t\t\t\t\t\ttry {\r\n");
      out.write("\t\t\t\t\t\t\t\t\tvar r = $.parseJSON(result);\r\n");
      out.write("\t\t\t\t\t\t\t\t\tif (r.success) {\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tdatagrid.datagrid('load');\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\td.dialog('destroy');\r\n");
      out.write("\t\t\t\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t\t\t\t\t$.messager.show({\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\ttitle : '提示',\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tmsg : r.msg\r\n");
      out.write("\t\t\t\t\t\t\t\t\t});\r\n");
      out.write("\t\t\t\t\t\t\t\t} catch (e) {\r\n");
      out.write("\t\t\t\t\t\t\t\t\t$.messager.alert('提示', result);\r\n");
      out.write("\t\t\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t\t\t\t//update-begin author:anchao for:防止form重复提交  date：20130310\r\n");
      out.write("\t\t\t\t\t\t\t\tformFlag =  true;\r\n");
      out.write("\t\t\t\t\t\t\t\t//update-end author:anchao for:防止form重复提交  date：20130310\r\n");
      out.write("\t\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t\t});\r\n");
      out.write("\t\t\t\t\t\t//update-begin author:anchao for:防止form重复提交  date：20130310\r\n");
      out.write("\t\t\t\t\t\tif(formFlag){\r\n");
      out.write("\t\t\t\t\t\t\tformFlag =  false;\r\n");
      out.write("\t\t\t\t\t\t//update-end author:anchao for:防止form重复提交  date：20130310\r\n");
      out.write("\t\t\t\t\t\t\t$('#noteEditForm').submit();\r\n");
      out.write("\t\t\t\t\t\t//update-begin author:anchao for:防止form重复提交  date：20130310\r\n");
      out.write("\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t\t//update-end author:anchao for:防止form重复提交  date：20130310\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t} ],\r\n");
      out.write("\t\t\t\tonClose : function() {\r\n");
      out.write("\t\t\t\t\t$(this).dialog('destroy');\r\n");
      out.write("\t\t\t\t},\r\n");
      out.write("\t\t\t\tonLoad : function() {\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t});\r\n");
      out.write("\t\t} else if (rows.length > 1) {\r\n");
      out.write("\t\t\t$.messager.alert('提示', '同一时间只能编辑一条记录！', 'error');\r\n");
      out.write("\t\t} else {\r\n");
      out.write("\t\t\t$.messager.alert('提示', '请选择要编辑的记录！', 'error');\r\n");
      out.write("\t\t}\r\n");
      out.write("\t}\r\n");
      out.write("\t//update-end author:gaoxingang for:优化将添加和修改页面分开  date：20130309\r\n");
      out.write("\t\r\n");
      out.write("\tfunction showCdesc(index) {\r\n");
      out.write("\t\tvar rows = datagrid.datagrid('getRows');\r\n");
      out.write("\t\tvar row = rows[index];\r\n");
      out.write("\t\t$.messager.progress({\r\n");
      out.write("\t\t\ttext : '数据加载中....',\r\n");
      out.write("\t\t\tinterval : 100\r\n");
      out.write("\t\t});\r\n");
      out.write("\t\t$.ajax({\r\n");
      out.write("\t\t\turl : 'noteAction!showDesc.action',\r\n");
      out.write("\t\t\tdata : {\r\n");
      out.write("\t\t\t\tobid : row.obid\r\n");
      out.write("\t\t\t},\r\n");
      out.write("\t\t\tdataType : 'json',\r\n");
      out.write("\t\t\tcache : false,\r\n");
      out.write("\t\t\tsuccess : function(response) {\r\n");
      out.write("\t\t\t\t$.messager.progress('close');\r\n");
      out.write("\t\t\t\tif (response && response.content) {\r\n");
      out.write("\t\t\t\t\tshowCdescDialog.find('div[name=cdesc]').html(response.content);\r\n");
      out.write("\t\t\t\t\tshowCdescDialog.dialog('open');\r\n");
      out.write("\t\t\t\t} else {\r\n");
      out.write("\t\t\t\t\t$.messager.alert('提示', '没有公告管理描述！', 'error');\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t});\r\n");
      out.write("\t\tdatagrid.datagrid('unselectAll');\r\n");
      out.write("\t}\r\n");
      out.write("</script>\r\n");
      out.write("</head>\r\n");
      out.write("<body class=\"easyui-layout\">\r\n");
      out.write("\t<div region=\"north\" border=\"false\" title=\"过滤条件\" collapsed=\"true\"  style=\"height: 60px;overflow: hidden;display: none;\" align=\"left\">\r\n");
      out.write("\t\t<form id=\"searchForm\">\r\n");
      out.write("\t\t\t<table class=\"tableForm datagrid-toolbar\" style=\"width: 100%;height: 100%;\">\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<td>标题</td>\r\n");
      out.write("\t\t\t\t\t<td><input name=\"title\" style=\"width:120px;\" /></td>\r\n");
      out.write("\t\t\t\t\t<td>内容</td>\r\n");
      out.write("\t\t\t\t\t<td><input name=\"content\" style=\"width:120px;\" /><td>\r\n");
      out.write("\t\t\t\t    <td><a href=\"javascript:void(0);\" class=\"easyui-linkbutton\" onclick=\"_search();\">过滤</a><a href=\"javascript:void(0);\" class=\"easyui-linkbutton\" onclick=\"cleanSearch();\">取消</a></td>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t</table>\r\n");
      out.write("\t\t</form>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t\r\n");
      out.write("\t<div region=\"center\" border=\"false\">\r\n");
      out.write("\t\t<table id=\"datagrid\"></table>\r\n");
      out.write("\t</div>\r\n");
      out.write("\r\n");
      out.write("\t<div id=\"menu\" class=\"easyui-menu\" style=\"width:120px;display: none;\">\r\n");
      out.write("\t\t<div onclick=\"add();\" iconCls=\"icon-add\">增加</div>\r\n");
      out.write("\t\t<div onclick=\"del();\" iconCls=\"icon-remove\">删除</div>\r\n");
      out.write("\t\t<div onclick=\"edit();\" iconCls=\"icon-edit\">编辑</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\r\n");
      out.write("\t<div id=\"showCdescDialog\" style=\"display: none;overflow: auto;width: 500px;height: 400px;\">\r\n");
      out.write("\t\t<div name=\"cdesc\"></div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
