/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.84
 * Generated at: 2018-03-27 01:57:00 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.business.stock;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.util.*;

public final class stock_002ddetail_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "/inc.jsp", out, false);
      out.write("\r\n");
      out.write("<style type=\"text/css\">\r\n");
      out.write("   .tdLeft{\r\n");
      out.write("      width:15%;\r\n");
      out.write("      text-align: right;\r\n");
      out.write("   }\r\n");
      out.write("   .tdRight{\r\n");
      out.write("      width:35%;\r\n");
      out.write("      text-align: left;\r\n");
      out.write("   }\r\n");
      out.write("    .comboxstock{\r\n");
      out.write("\t   width:470px;\r\n");
      out.write("\t   border:0px solid #cfcfcf;\r\n");
      out.write("\t   border-collapse: collapse;\r\n");
      out.write("\t   margin:0px;\r\n");
      out.write("\t   table-layout:fixed;\r\n");
      out.write("\t}\r\n");
      out.write("\t.comboxstock td{\r\n");
      out.write("\t   overflow:hidden;\r\n");
      out.write("\t}\r\n");
      out.write("</style>\r\n");
      out.write("<script type=\"text/javascript\" charset=\"utf-8\">\r\n");
      out.write("    var searchForm;\r\n");
      out.write("\tvar datagrid;\r\n");
      out.write("\tvar stockAddDialog;\r\n");
      out.write("\tvar stockAddForm;\r\n");
      out.write("\tvar cdescAdd;\r\n");
      out.write("\tvar stockEditDialog;\r\n");
      out.write("\tvar stockEditForm;\r\n");
      out.write("\tvar cdescEdit;\r\n");
      out.write("\tvar showCdescDialog;\r\n");
      out.write("\tvar iframeDialog;\r\n");
      out.write("\tvar formFlag = true;\r\n");
      out.write("\t$(function() {\r\n");
      out.write("\t    //查询列表\t\r\n");
      out.write("\t    searchForm = $('#searchForm').form();\r\n");
      out.write("\t\tdatagrid = $('#datagrid').datagrid({\r\n");
      out.write("\t\t\turl : 'stockAction!datagridDetail.action',\r\n");
      out.write("\t\t\ttitle : '库存明细列表',\r\n");
      out.write("\t\t\tpagination : true,\r\n");
      out.write("\t\t\tpagePosition : 'bottom',\r\n");
      out.write("\t\t\trownumbers : true,\r\n");
      out.write("\t\t\tpageSize : 10,\r\n");
      out.write("\t\t\tpageList : [ 10, 20, 30, 40 ],\r\n");
      out.write("\t\t\tfit : true,\r\n");
      out.write("\t\t\tfitColumns : true,\r\n");
      out.write("\t\t\tsingleSelect:true,\r\n");
      out.write("\t\t\tnowrap : true,\r\n");
      out.write("\t\t\tborder : false,\r\n");
      out.write("\t\t\tidField : 'stockkey',\r\n");
      out.write("\t\t\tsortName : '',\r\n");
      out.write("\t\t\tsortOrder : 'desc',\r\n");
      out.write("\t\t\tcolumns : [ [ \r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t   {field:'depotid',title:'仓库名称',align:'center',sortable:true,width:80,\r\n");
      out.write("\t\t\t\t\tformatter:function(value,row,index){\r\n");
      out.write("\t\t\t\t\t\treturn row.depotpage.depotname;\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t},\t\t\t\t\r\n");
      out.write("\t\t\t   {field:'articlename',title:'品种编码',align:'center',width:80,\r\n");
      out.write("\t\t\t\t\tformatter:function(value,row,index){\r\n");
      out.write("\t\t\t\t\t\treturn row.articleid;\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t},\t\t\t\t\r\n");
      out.write("\t\t\t   {field:'articleid',title:'品种名称',align:'center',sortable:true,width:120,\r\n");
      out.write("\t\t\t\t\tformatter:function(value,row,index){\r\n");
      out.write("\t\t\t\t\t\treturn row.articlepage.articlename;\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t},\t\t\t\t\r\n");
      out.write("\t\t\t   {field:'articlespec',title:'品种规格',align:'center',sortable:false,width:80,\r\n");
      out.write("\t\t\t\t\tformatter:function(value,row,index){\r\n");
      out.write("\t\t\t\t\t\treturn row.articlepage.articlespec;\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t},\t\t\t\t\r\n");
      out.write("\t\t\t   {field:'factory',title:'厂家',align:'center',sortable:false,width:90,\r\n");
      out.write("\t\t\t\t\tformatter:function(value,row,index){\r\n");
      out.write("\t\t\t\t\t\treturn row.articlepage.factory;\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t},\t\t\t\t\r\n");
      out.write("\t\t\t   {field:'serial',title:'批号',align:'center',sortable:true,width:80,\r\n");
      out.write("\t\t\t\t\tformatter:function(value,row,index){\r\n");
      out.write("\t\t\t\t\t\treturn row.serial;\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t},\t\t\t\t\r\n");
      out.write("\t\t\t   {field:'num',title:'数量',align:'center',sortable:true,width:80,\r\n");
      out.write("\t\t\t\t\tformatter:function(value,row,index){\r\n");
      out.write("\t\t\t\t\t\treturn row.num;\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t},\t\t\t\t\r\n");
      out.write("\t\t\t   {field:'costprice',title:'成本价',align:'center',sortable:true,width:80,\r\n");
      out.write("\t\t\t\t\tformatter:function(value,row,index){\r\n");
      out.write("\t\t\t\t\t\treturn row.costprice;\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t},\t\t\t\t\r\n");
      out.write("\t\t\t   {field:'expiredate',title:'有效期',align:'center',sortable:true,width:80,\r\n");
      out.write("\t\t\t\t\tformatter:function(value,row,index){\r\n");
      out.write("\t\t\t\t\t\treturn dateFormatYMD(row.expiredate);\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t}\t\t\t\t\r\n");
      out.write("\t\t\t ] ],\r\n");
      out.write("\t\t\ttoolbar : [ {\r\n");
      out.write("\t\t\t\ttext : '刷新',\r\n");
      out.write("\t\t\t\ticonCls : 'icon-undo',\r\n");
      out.write("\t\t\t\thandler : function() {\r\n");
      out.write("\t\t\t\t\tdatagrid.datagrid('reload');\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t}, '-' ],\r\n");
      out.write("\t\t\tonRowContextMenu : function(e, rowIndex, rowData) {\r\n");
      out.write("\t\t\t\te.preventDefault();\r\n");
      out.write("\t\t\t\t$(this).datagrid('unselectAll');\r\n");
      out.write("\t\t\t\t$(this).datagrid('selectRow', rowIndex);\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t});\r\n");
      out.write("\r\n");
      out.write("\t\tstockAddForm = $('#stockAddForm').form({\r\n");
      out.write("\t\t\turl : 'stockAction!add.action',\r\n");
      out.write("\t\t\tsuccess : function(data) {\r\n");
      out.write("\t\t\t\tvar json = $.parseJSON(data);\r\n");
      out.write("\t\t\t\tif (json && json.success) {\r\n");
      out.write("\t\t\t\t\t$.messager.show({\r\n");
      out.write("\t\t\t\t\t\ttitle : '成功',\r\n");
      out.write("\t\t\t\t\t\tmsg : json.msg\r\n");
      out.write("\t\t\t\t\t});\r\n");
      out.write("\t\t\t\t\tdatagrid.datagrid('reload');\r\n");
      out.write("\t\t\t\t\tstockAddDialog.dialog('close');\r\n");
      out.write("\t\t\t\t} else {\r\n");
      out.write("\t\t\t\t\t$.messager.show({\r\n");
      out.write("\t\t\t\t\t\ttitle : '失败',\r\n");
      out.write("\t\t\t\t\t\tmsg : '操作失败！'\r\n");
      out.write("\t\t\t\t\t});\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t\tformFlag = true ;\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t});\r\n");
      out.write("\r\n");
      out.write("\t\tstockAddDialog = $('#stockAddDialog').show().dialog({\r\n");
      out.write("\t\t\ttitle : '添加库存信息',\r\n");
      out.write("\t\t\tmodal : true,\r\n");
      out.write("\t\t\tclosed : true,\r\n");
      out.write("\t\t\tmaximizable : true,\r\n");
      out.write("\t\t\tbuttons : [ {\r\n");
      out.write("\t\t\t\ttext : '添加',\r\n");
      out.write("\t\t\t\thandler : function() {\r\n");
      out.write("\t\t\t\t\tif(formFlag){\r\n");
      out.write("\t\t\t\t\t\tformFlag = false ;\r\n");
      out.write("\t\t\t\t\t\tstockAddForm.submit();\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t} ]\r\n");
      out.write("\t\t});\r\n");
      out.write("\r\n");
      out.write("\t\tcdescAdd = $('#cdescAdd').xheditor({\r\n");
      out.write("\t\t\ttools : 'mini',\r\n");
      out.write("\t\t\thtml5Upload : true,\r\n");
      out.write("\t\t\tupMultiple : 4,\r\n");
      out.write("\t\t\tupLinkUrl : 'stockAction!upload.action',\r\n");
      out.write("\t\t\tupLinkExt : 'zip,rar,txt,doc,docx,xls,xlsx',\r\n");
      out.write("\t\t\tupImgUrl : 'stockAction!upload.action',\r\n");
      out.write("\t\t\tupImgExt : 'jpg,jpeg,gif,png'\r\n");
      out.write("\t\t});\r\n");
      out.write("\r\n");
      out.write("\t\tstockEditForm = $('#stockEditForm').form({\r\n");
      out.write("\t\t\turl : 'stockAction!edit.action',\r\n");
      out.write("\t\t\tsuccess : function(data) {\r\n");
      out.write("\t\t\t\tvar json = $.parseJSON(data);\r\n");
      out.write("\t\t\t\tif (json && json.success) {\r\n");
      out.write("\t\t\t\t\t$.messager.show({\r\n");
      out.write("\t\t\t\t\t\ttitle : '成功',\r\n");
      out.write("\t\t\t\t\t\tmsg : json.msg\r\n");
      out.write("\t\t\t\t\t});\r\n");
      out.write("\t\t\t\t\tdatagrid.datagrid('reload');\r\n");
      out.write("\t\t\t\t\tstockEditDialog.dialog('close');\r\n");
      out.write("\t\t\t\t} else {\r\n");
      out.write("\t\t\t\t\t$.messager.show({\r\n");
      out.write("\t\t\t\t\t\ttitle : '失败',\r\n");
      out.write("\t\t\t\t\t\tmsg : '操作失败！'\r\n");
      out.write("\t\t\t\t\t});\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t\tformFlag = true ;\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t});\r\n");
      out.write("\r\n");
      out.write("\t\tstockEditDialog = $('#stockEditDialog').show().dialog({\r\n");
      out.write("\t\t\ttitle : '编辑库存信息',\r\n");
      out.write("\t\t\tmodal : true,\r\n");
      out.write("\t\t\tclosed : true,\r\n");
      out.write("\t\t\tmaximizable : true,\r\n");
      out.write("\t\t\tbuttons : [ {\r\n");
      out.write("\t\t\t\ttext : '编辑',\r\n");
      out.write("\t\t\t\thandler : function() {\r\n");
      out.write("\t\t\t\t\tif(formFlag){\r\n");
      out.write("\t\t\t\t\t\tformFlag = false ;\r\n");
      out.write("\t\t\t\t\t\tstockEditForm.submit();\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t} ]\r\n");
      out.write("\t\t});\r\n");
      out.write("\r\n");
      out.write("\t\tcdescEdit = $('#cdescEdit').xheditor({\r\n");
      out.write("\t\t\ttools : 'mini',\r\n");
      out.write("\t\t\thtml5Upload : true,\r\n");
      out.write("\t\t\tupMultiple : 4,\r\n");
      out.write("\t\t\tupLinkUrl : 'stockAction!upload.action',\r\n");
      out.write("\t\t\tupLinkExt : 'zip,rar,txt,doc,docx,xls,xlsx',\r\n");
      out.write("\t\t\tupImgUrl : 'stockAction!upload.action',\r\n");
      out.write("\t\t\tupImgExt : 'jpg,jpeg,gif,png'\r\n");
      out.write("\t\t});\r\n");
      out.write("\r\n");
      out.write("\t\tshowCdescDialog = $('#showCdescDialog').show().dialog({\r\n");
      out.write("\t\t\ttitle : '库存信息描述',\r\n");
      out.write("\t\t\tmodal : true,\r\n");
      out.write("\t\t\tclosed : true,\r\n");
      out.write("\t\t\tmaximizable : true\r\n");
      out.write("\t\t});\r\n");
      out.write("\r\n");
      out.write("\t\tiframeDialog = $('#iframeDialog').show().dialog({\r\n");
      out.write("\t\t\ttitle : 'POP弹出页面',\r\n");
      out.write("\t\t\tmodal : true,\r\n");
      out.write("\t\t\tclosed : true,\r\n");
      out.write("\t\t\tmaximizable : true\r\n");
      out.write("\t\t});\r\n");
      out.write("\t});\r\n");
      out.write("\r\n");
      out.write("\tfunction _search() {\r\n");
      out.write("\t\tdatagrid.datagrid('load', sy.serializeObject(searchForm));\r\n");
      out.write("\t}\r\n");
      out.write("\tfunction cleanSearch() {\r\n");
      out.write("\t\tdatagrid.datagrid('load', {});\r\n");
      out.write("\t\tsearchForm.find('input').val('');\r\n");
      out.write("\t}\r\n");
      out.write("\tfunction add() {\r\n");
      out.write("\t\tstockAddForm.find('input,textarea').val('');\r\n");
      out.write("\t\t$('div.validatebox-tip').remove();\r\n");
      out.write("\t\tstockAddDialog.dialog('open');\r\n");
      out.write("\t}\r\n");
      out.write("\tfunction del() {\r\n");
      out.write("\t\tvar rows = datagrid.datagrid('getSelections');\r\n");
      out.write("\t\tvar ids = [];\r\n");
      out.write("\t\tif (rows.length > 0) {\r\n");
      out.write("\t\t\t$.messager.confirm('请确认', '您要删除当前所选项目？', function(r) {\r\n");
      out.write("\t\t\t\tif (r) {\r\n");
      out.write("\t\t\t\t\tfor ( var i = 0; i < rows.length; i++) {\r\n");
      out.write("\t\t\t\t\t\tids.push(rows[i].stockkey);\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t$.ajax({\r\n");
      out.write("\t\t\t\t\t\turl : 'stockAction!delete.action',\r\n");
      out.write("\t\t\t\t\t\tdata : {\r\n");
      out.write("\t\t\t\t\t\t\tids : ids.join(',')\r\n");
      out.write("\t\t\t\t\t\t},\r\n");
      out.write("\t\t\t\t\t\tdataType : 'json',\r\n");
      out.write("\t\t\t\t\t\tsuccess : function(response) {\r\n");
      out.write("\t\t\t\t\t\t\tdatagrid.datagrid('load');\r\n");
      out.write("\t\t\t\t\t\t\tdatagrid.datagrid('unselectAll');\r\n");
      out.write("\t\t\t\t\t\t\t$.messager.show({\r\n");
      out.write("\t\t\t\t\t\t\t\ttitle : '提示',\r\n");
      out.write("\t\t\t\t\t\t\t\tmsg : '删除成功！'\r\n");
      out.write("\t\t\t\t\t\t\t});\r\n");
      out.write("\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t});\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t});\r\n");
      out.write("\t\t} else {\r\n");
      out.write("\t\t\t$.messager.alert('提示', '请选择要删除的记录！', 'error');\r\n");
      out.write("\t\t}\r\n");
      out.write("\t}\r\n");
      out.write("\tfunction edit() {\r\n");
      out.write("\t\tvar rows = datagrid.datagrid('getSelections');\r\n");
      out.write("\t\tif (rows.length == 1) {\r\n");
      out.write("\t\t\t$.messager.progress({\r\n");
      out.write("\t\t\t\ttext : '数据加载中....',\r\n");
      out.write("\t\t\t\tinterval : 100\r\n");
      out.write("\t\t\t});\r\n");
      out.write("\t\t\t$.ajax({\r\n");
      out.write("\t\t\t\turl : 'stockAction!showDesc.action',\r\n");
      out.write("\t\t\t\tdata : {\r\n");
      out.write("\t\t\t\t\tstockkey : rows[0].stockkey\r\n");
      out.write("\t\t\t\t},\r\n");
      out.write("\t\t\t\tdataType : 'json',\r\n");
      out.write("\t\t\t\tcache : false,\r\n");
      out.write("\t\t\t\tsuccess : function(response) {\r\n");
      out.write("\t\t\t\t\tstockEditForm.find('input,textarea').val('');\r\n");
      out.write("\t\t\t\t\tstockEditForm.form('load', response);\r\n");
      out.write("\t\t\t\t\t$('div.validatebox-tip').remove();\r\n");
      out.write("\t\t\t\t\tstockEditDialog.dialog('open');\r\n");
      out.write("\t\t\t\t\t$.messager.progress('close');\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t});\r\n");
      out.write("\t\t} else {\r\n");
      out.write("\t\t\t$.messager.alert('提示', '请选择一项要编辑的记录！', 'error');\r\n");
      out.write("\t\t}\r\n");
      out.write("\t}\r\n");
      out.write("\tfunction showCdesc(index) {\r\n");
      out.write("\t\tvar rows = datagrid.datagrid('getRows');\r\n");
      out.write("\t\tvar row = rows[index];\r\n");
      out.write("\t\t$.messager.progress({\r\n");
      out.write("\t\t\ttext : '数据加载中....',\r\n");
      out.write("\t\t\tinterval : 100\r\n");
      out.write("\t\t});\r\n");
      out.write("\t\t$.ajax({\r\n");
      out.write("\t\t\turl : 'stockAction!showDesc.action',\r\n");
      out.write("\t\t\tdata : {\r\n");
      out.write("\t\t\t\tstockkey : row.stockkey\r\n");
      out.write("\t\t\t},\r\n");
      out.write("\t\t\tdataType : 'json',\r\n");
      out.write("\t\t\tcache : false,\r\n");
      out.write("\t\t\tsuccess : function(response) {\r\n");
      out.write("\t\t\t\tif (response && response.cdesc) {\r\n");
      out.write("\t\t\t\t\tshowCdescDialog.find('div[name=cdesc]').html(response.cdesc);\r\n");
      out.write("\t\t\t\t\tshowCdescDialog.dialog('open');\r\n");
      out.write("\t\t\t\t} else {\r\n");
      out.write("\t\t\t\t\t$.messager.alert('提示', '没有库存信息描述！', 'error');\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t\t$.messager.progress('close');\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t});\r\n");
      out.write("\t\tdatagrid.datagrid('unselectAll');\r\n");
      out.write("\t}\r\n");
      out.write("</script>\r\n");
      out.write("</head>\r\n");
      out.write("<body class=\"easyui-layout\">\r\n");
      out.write("\t<div region=\"north\" border=\"false\" title=\"过滤条件\" collapsed=\"false\"  style=\"height: 60px;overflow: hidden;\" align=\"left\">\r\n");
      out.write("\t\t<form id=\"searchForm\">\r\n");
      out.write("\t\t\t<table class=\"tableForm datagrid-toolbar\" style=\"width: 100%;height: 100%;\">\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<td>仓库</td>\r\n");
      out.write("\t\t\t\t\t<td>\r\n");
      out.write("\t\t\t\t\t <select id=\"depotid\" name=\"depotid\" type=\"text\"  class=\"easyui-combobox\" data-options=\"\r\n");
      out.write("\t\t \t\t\t\t\t\t       url:'depotAction!combox.action',\r\n");
      out.write("\t\t\t\t\t\t\t\t      \t valueField:'depotid',\r\n");
      out.write("\t\t\t\t\t\t\t\t         textField:'depotname',\r\n");
      out.write("\t\t\t\t\t\t                editable:false\r\n");
      out.write("\t\t \t\t\t\t\t\t       \"  missingMessage=\"请填写供仓库\"  style=\"width: 125px;\">\r\n");
      out.write("\t\t \t\t    </select>\r\n");
      out.write("\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t<td>品种</td>\r\n");
      out.write("\t\t\t\t\t<td>\r\n");
      out.write("\t\t\t\t\t   <select  name=\"articleid\" type=\"text\"  class=\"easyui-combobox\" data-options=\"\r\n");
      out.write("\t\t \t\t\t\t\t\t        url:'articleAction!getArticleForStockIn.action',\r\n");
      out.write("\t\t\t\t\t\t\t\t      \tvalueField:'articleid',\r\n");
      out.write("\t\t\t\t\t\t\t\t        textField:'articlename',\r\n");
      out.write("\t\t\t\t\t\t                panelHeight:90,\r\n");
      out.write("\t\t\t\t\t\t                panelWidth:500,\r\n");
      out.write("\t\t\t\t\t\t                filter: function(q, row){\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\tvar opts = $(this).combobox('options');\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\treturn row[opts.textField].indexOf(q)!=-1||row['articlealias'].indexOf(q)!=-1;\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t},\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tformatter:function(row){\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t   var factoryname = row.factory;\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t   if (row.factory.length>7) factoryname = row.factory.substring(0,7);\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t   var articlespec = row.articlespec;\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t   if (row.articlespec.length>12) articlespec = row.articlespec.substring(0,12);\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t   return '<table  class=comboxstock ><tr><td >'+row.articlename+'</td><td width=110px;>'+articlespec+'</td><td width=100px;>'+factoryname+'</td><td width=40px;>'+row.unitname+'</td></tr></table>';\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t}\r\n");
      out.write("\t\t \t\t\t\t\t\t       \"  missingMessage=\"请填写品种\"  style=\"width:130px;\" >\r\n");
      out.write("\t\t \t\t\t\t</select>\r\n");
      out.write("\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t<td>批号</td>\r\n");
      out.write("\t\t\t\t\t<td><input name=\"serial\" style=\"width:120px;\" class=\"easyui-validatebox\"/></td>\r\n");
      out.write("\t\t\t\t\t<td>库存数量<=</td>\r\n");
      out.write("\t\t\t\t\t<td><input name=\"num\" style=\"width:120px;\" class=\"easyui-numberbox\"/></td>\r\n");
      out.write("\t\t\t\t\t<td>有效期限<=</td>\r\n");
      out.write("\t\t\t\t\t<td>\r\n");
      out.write("\t\t\t\t\t   <input id=\"begindate\" name=\"ccreatedatetimeStart\" style=\"width:90px;\" class=\"easyui-datebox\"/>\r\n");
      out.write("\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t    <td><a href=\"javascript:void(0);\" class=\"easyui-linkbutton\" onclick=\"_search();\">过滤</a><a href=\"javascript:void(0);\" class=\"easyui-linkbutton\" onclick=\"cleanSearch();\">取消</a></td>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t</table>\r\n");
      out.write("\t\t</form>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t\r\n");
      out.write("\t<div region=\"center\" border=\"false\">\r\n");
      out.write("\t\t<table id=\"datagrid\"></table>\r\n");
      out.write("\t</div>\r\n");
      out.write("\r\n");
      out.write("\t<div id=\"menu\" class=\"easyui-menu\" style=\"width:120px;display: none;\">\r\n");
      out.write("\t\t<div onclick=\"add();\" iconCls=\"icon-add\">增加</div>\r\n");
      out.write("\t\t<div onclick=\"del();\" iconCls=\"icon-remove\">删除</div>\r\n");
      out.write("\t\t<div onclick=\"edit();\" iconCls=\"icon-edit\">编辑</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\r\n");
      out.write("\t<div id=\"stockAddDialog\" style=\"display: none;width: 500px;height: 300px;padding:10px;\" align=\"center\">\r\n");
      out.write("\t\t<form id=\"stockAddForm\" method=\"post\">\r\n");
      out.write("\t\t\t<table class=\"tableForm\">\r\n");
      out.write("\t\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t \t\t\t\t\t\t<td class=\"tdLeft\">仓库</td>\r\n");
      out.write("\t\t \t\t\t\t\t\t<td class=\"tdRight\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<input name=\"depotid\" type=\"text\" maxlength=\"5\" class=\"easyui-validatebox\" data-options=\"required:true\" missingMessage=\"请填写仓库ID\"  style=\"width: 155px;\"/>\r\n");
      out.write("\t\t\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t \t\t\t\t\t\t<td class=\"tdLeft\">品种</td>\r\n");
      out.write("\t\t \t\t\t\t\t\t<td class=\"tdRight\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<input name=\"articleid\" type=\"text\" maxlength=\"20\" class=\"easyui-validatebox\" data-options=\"required:true\" missingMessage=\"请填写品种ID\"  style=\"width: 155px;\"/>\r\n");
      out.write("\t\t\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t \t\t\t\t\t\t<td class=\"tdLeft\">批号</td>\r\n");
      out.write("\t\t \t\t\t\t\t\t<td class=\"tdRight\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<input name=\"serial\" type=\"text\" maxlength=\"20\" class=\"easyui-validatebox\" data-options=\"required:true\" missingMessage=\"请填写批号\"  style=\"width: 155px;\"/>\r\n");
      out.write("\t\t\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t \t\t\t\t\t\t<td class=\"tdLeft\">数量</td>\r\n");
      out.write("\t\t \t\t\t\t\t\t<td class=\"tdRight\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<input name=\"num\" type=\"text\" maxlength=\"\" class=\"easyui-numberbox\" data-options=\"required:true,precision:2,groupSeparator:','\" missingMessage=\"请填写数量\"  style=\"width: 155px;\"/>\r\n");
      out.write("\t\t\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t \t\t\t\t\t\t<td class=\"tdLeft\">成本价</td>\r\n");
      out.write("\t\t \t\t\t\t\t\t<td class=\"tdRight\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<input name=\"costprice\" type=\"text\" maxlength=\"\" class=\"easyui-numberbox\" data-options=\"required:true,precision:2,groupSeparator:','\" missingMessage=\"请填写成本价\"  style=\"width: 155px;\"/>\r\n");
      out.write("\t\t\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t \t\t\t\t\t\t<td class=\"tdLeft\">有效期</td>\r\n");
      out.write("\t\t \t\t\t\t\t\t<td class=\"tdRight\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<input name=\"expiredate\" type=\"text\" maxlength=\"\" class=\"easyui-datebox\" data-options=\"required:true\" missingMessage=\"请填写有效期\"  style=\"width: 155px;\"/>\r\n");
      out.write("\t\t\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t</table>\r\n");
      out.write("\t\t</form>\r\n");
      out.write("\t</div>\r\n");
      out.write("\r\n");
      out.write("\t<div id=\"stockEditDialog\" style=\"display: none;width: 500px;height: 300px;padding:10px;\" align=\"center\">\r\n");
      out.write("\t\t<form id=\"stockEditForm\" method=\"post\">\r\n");
      out.write("\t\t\t<input type=\"hidden\" name=\"stockkey\" />\r\n");
      out.write("\t\t\t<table class=\"tableForm\">\r\n");
      out.write("\t\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t \t\t\t\t\t\t<td class=\"tdLeft\">仓库</td>\r\n");
      out.write("\t\t \t\t\t\t\t\t<td class=\"tdRight\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<input name=\"depotid\" type=\"text\" maxlength=\"5\" class=\"easyui-validatebox\" data-options=\"required:true\" missingMessage=\"请填写仓库ID\"  style=\"width: 155px;\"/>\r\n");
      out.write("\t\t\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t \t\t\t\t\t\t<td class=\"tdLeft\">品种</td>\r\n");
      out.write("\t\t \t\t\t\t\t\t<td class=\"tdRight\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<input name=\"articleid\" type=\"text\" maxlength=\"20\" class=\"easyui-validatebox\" data-options=\"required:true\" missingMessage=\"请填写品种ID\"  style=\"width: 155px;\"/>\r\n");
      out.write("\t\t\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t \t\t\t\t\t\t<td class=\"tdLeft\">批号</td>\r\n");
      out.write("\t\t \t\t\t\t\t\t<td class=\"tdRight\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<input name=\"serial\" type=\"text\" maxlength=\"20\" class=\"easyui-validatebox\" data-options=\"required:true\" missingMessage=\"请填写批号\"  style=\"width: 155px;\"/>\r\n");
      out.write("\t\t\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t \t\t\t\t\t\t<td class=\"tdLeft\">数量</td>\r\n");
      out.write("\t\t \t\t\t\t\t\t<td class=\"tdRight\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<input name=\"num\" type=\"text\" maxlength=\"\" class=\"easyui-numberbox\" data-options=\"required:true,precision:2,groupSeparator:','\" missingMessage=\"请填写数量\"  style=\"width: 155px;\"/>\r\n");
      out.write("\t\t\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t \t\t\t\t\t\t<td class=\"tdLeft\">成本价</td>\r\n");
      out.write("\t\t \t\t\t\t\t\t<td class=\"tdRight\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<input name=\"costprice\" type=\"text\" maxlength=\"\" class=\"easyui-numberbox\" data-options=\"required:true,precision:2,groupSeparator:','\" missingMessage=\"请填写成本价\"  style=\"width: 155px;\"/>\r\n");
      out.write("\t\t\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t \t\t\t\t\t\t<td class=\"tdLeft\">有效期</td>\r\n");
      out.write("\t\t \t\t\t\t\t\t<td class=\"tdRight\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<input name=\"expiredate\" type=\"text\" maxlength=\"\" class=\"easyui-datebox\" data-options=\"\" missingMessage=\"请填写有效期\"  style=\"width: 155px;\"/>\r\n");
      out.write("\t\t\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t</table>\r\n");
      out.write("\t\t</form>\r\n");
      out.write("\t</div>\r\n");
      out.write("\r\n");
      out.write("\t<div id=\"showCdescDialog\" style=\"display: none;overflow: auto;width: 500px;height: 400px;\">\r\n");
      out.write("\t\t<div name=\"cdesc\"></div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t\r\n");
      out.write("\t<div id=\"iframeDialog\" style=\"display: none;overflow: auto;width: 600px;height: 400px;\">\r\n");
      out.write("\t<iframe name=\"iframe\" id=\"iframe\" src=\"\"  scrolling=\"auto\" frameborder=\"0\" style=\"width:100%;height:100%;\">\r\n");
      out.write("    </iframe>\r\n");
      out.write("</div>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
