/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.84
 * Generated at: 2018-03-27 01:56:11 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.layout;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.util.*;

public final class center_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<script type=\"text/javascript\" charset=\"utf-8\">\r\n");
      out.write("\tvar centerTabs;\r\n");
      out.write("\tvar tabsMenu;\r\n");
      out.write("\t$(function() {\r\n");
      out.write("\t\ttabsMenu = $('#tabsMenu').menu({\r\n");
      out.write("\t\t\tonClick : function(item) {\r\n");
      out.write("\t\t\t\tvar curTabTitle = $(this).data('tabTitle');\r\n");
      out.write("\t\t\t\tvar type = $(item.target).attr('type');\r\n");
      out.write("\r\n");
      out.write("\t\t\t\tif (type === 'refresh') {\r\n");
      out.write("\t\t\t\t\trefreshTab(curTabTitle);\r\n");
      out.write("\t\t\t\t\treturn;\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\r\n");
      out.write("\t\t\t\tif (type === 'close') {\r\n");
      out.write("\t\t\t\t\tvar t = centerTabs.tabs('getTab', curTabTitle);\r\n");
      out.write("\t\t\t\t\tif (t.panel('options').closable) {\r\n");
      out.write("\t\t\t\t\t\tcenterTabs.tabs('close', curTabTitle);\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\treturn;\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\r\n");
      out.write("\t\t\t\tvar allTabs = centerTabs.tabs('tabs');\r\n");
      out.write("\t\t\t\tvar closeTabsTitle = [];\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t$.each(allTabs, function() {\r\n");
      out.write("\t\t\t\t\tvar opt = $(this).panel('options');\r\n");
      out.write("\t\t\t\t\tif (opt.closable && opt.title != curTabTitle && type === 'closeOther') {\r\n");
      out.write("\t\t\t\t\t\tcloseTabsTitle.push(opt.title);\r\n");
      out.write("\t\t\t\t\t} else if (opt.closable && type === 'closeAll') {\r\n");
      out.write("\t\t\t\t\t\tcloseTabsTitle.push(opt.title);\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t});\r\n");
      out.write("\r\n");
      out.write("\t\t\t\tfor ( var i = 0; i < closeTabsTitle.length; i++) {\r\n");
      out.write("\t\t\t\t\tcenterTabs.tabs('close', closeTabsTitle[i]);\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t});\r\n");
      out.write("\r\n");
      out.write("\t\tcenterTabs = $('#centerTabs').tabs({\r\n");
      out.write("\t\t\tfit : true,\r\n");
      out.write("\t\t\tborder : false,\r\n");
      out.write("\t\t\tonContextMenu : function(e, title) {\r\n");
      out.write("\t\t\t\te.preventDefault();\r\n");
      out.write("\t\t\t\ttabsMenu.menu('show', {\r\n");
      out.write("\t\t\t\t\tleft : e.pageX,\r\n");
      out.write("\t\t\t\t\ttop : e.pageY\r\n");
      out.write("\t\t\t\t}).data('tabTitle', title);\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t});\r\n");
      out.write("\t});\r\n");
      out.write("\t\r\n");
      out.write("\tfunction refreshTab(title) {\r\n");
      out.write("\t\tvar tab = centerTabs.tabs('getTab', title);\r\n");
      out.write("\t\tcenterTabs.tabs('update', {\r\n");
      out.write("\t\t\ttab : tab,\r\n");
      out.write("\t\t\toptions : tab.panel('options')\r\n");
      out.write("\t\t});\r\n");
      out.write("\t}\r\n");
      out.write("\tfunction addTab(node) {\r\n");
      out.write("\t\tif (centerTabs.tabs('exists', node.text)) {\r\n");
      out.write("\t\t\t//refreshTab(node.text); //增加左侧菜单点击刷新功能 libc 2012-9-24\r\n");
      out.write("\t\t\tcenterTabs.tabs('select', node.text);\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t} else {\r\n");
      out.write("\t\t\tif (node.attributes.url && node.attributes.url.length > 0) {\r\n");
      out.write("\t\t\t\t//if (node.attributes.url.indexOf('!druid.action') == -1) {/*数据源监控页面不需要开启等待提示*/\r\n");
      out.write("\t\t\t\t\t$.messager.progress({\r\n");
      out.write("\t\t\t\t\t\ttext : '正在加载...',\r\n");
      out.write("\t\t\t\t\t\tinterval : 100\r\n");
      out.write("\t\t\t\t\t});\r\n");
      out.write("\t\t\t\t\twindow.setTimeout(function() {\r\n");
      out.write("\t\t\t\t\t\ttry {\r\n");
      out.write("\t\t\t\t\t\t\t$.messager.progress('close');\r\n");
      out.write("\t\t\t\t\t\t} catch (e) {\r\n");
      out.write("\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t}, 0);\r\n");
      out.write("\t\t\t\t//\t}\r\n");
      out.write("\t\t\t\tcenterTabs.tabs('add', {\r\n");
      out.write("\t\t\t\t\ttitle : node.text,\r\n");
      out.write("\t\t\t\t\tclosable : true,\r\n");
      out.write("\t\t\t\t\ticonCls : node.iconCls,\r\n");
      out.write("\t\t\t\t\tcontent : '<iframe src=\"' + node.attributes.url + '\" frameborder=\"0\" style=\"border:0;width:100%;height:99.4%;\"></iframe>',\r\n");
      out.write("\t\t\t\t\ttools : [ {\r\n");
      out.write("\t\t\t\t\t\ticonCls : 'icon-mini-refresh',\r\n");
      out.write("\t\t\t\t\t\thandler : function() {\r\n");
      out.write("\t\t\t\t\t\t\trefreshTab(node.text);\r\n");
      out.write("\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t} ]\r\n");
      out.write("\t\t\t\t});\r\n");
      out.write("\t\t\t} else {\r\n");
      out.write("\t\t\t\tcenterTabs.tabs('add', {\r\n");
      out.write("\t\t\t\t\ttitle : node.text,\r\n");
      out.write("\t\t\t\t\tclosable : true,\r\n");
      out.write("\t\t\t\t\ticonCls : node.iconCls,\r\n");
      out.write("\t\t\t\t\tcontent : '<iframe src=\"error/err.jsp\" frameborder=\"0\" style=\"border:0;width:100%;height:99.4%;\"></iframe>',\r\n");
      out.write("\t\t\t\t\ttools : [ {\r\n");
      out.write("\t\t\t\t\t\ticonCls : 'icon-mini-refresh',\r\n");
      out.write("\t\t\t\t\t\thandler : function() {\r\n");
      out.write("\t\t\t\t\t\t\trefreshTab(node.text);\r\n");
      out.write("\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t} ]\r\n");
      out.write("\t\t\t\t});\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t}\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\t//--功能描述：左侧菜单添加tab（手风琴样式）\r\n");
      out.write("\tfunction addTabs(text,url,ciconCls) {\r\n");
      out.write("\t\tif (centerTabs.tabs('exists', text)) {\r\n");
      out.write("\t\t\t//refreshTab(text); //增加左侧菜单点击刷新功能 libc 2012-9-24\r\n");
      out.write("\t\t\tcenterTabs.tabs('select', text);\r\n");
      out.write("\t\t} else {\r\n");
      out.write("\t\t\tif (url && url.length > 0) {\r\n");
      out.write("\t\t\t\t//if (node.attributes.url.indexOf('!druid.action') == -1) {/*数据源监控页面不需要开启等待提示*/\r\n");
      out.write("\t\t\t\t\t$.messager.progress({\r\n");
      out.write("\t\t\t\t\t\ttext : '正在加载...',\r\n");
      out.write("\t\t\t\t\t\tinterval : 100\r\n");
      out.write("\t\t\t\t\t});\r\n");
      out.write("\t\t\t\t\twindow.setTimeout(function() {\r\n");
      out.write("\t\t\t\t\t\ttry {\r\n");
      out.write("\t\t\t\t\t\t\t$.messager.progress('close');\r\n");
      out.write("\t\t\t\t\t\t} catch (e) {\r\n");
      out.write("\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t}, 0);\r\n");
      out.write("\t\t\t\t//\t}\r\n");
      out.write("\t\t\t\tcenterTabs.tabs('add', {\r\n");
      out.write("\t\t\t\t\ttitle : text,\r\n");
      out.write("\t\t\t\t\tclosable : true,\r\n");
      out.write("\t\t\t\t\ticonCls : ciconCls,\r\n");
      out.write("\t\t\t\t\tcontent : '<iframe src=\"' + url + '\" frameborder=\"0\" style=\"border:0;width:100%;height:99.4%;\"></iframe>',\r\n");
      out.write("\t\t\t\t\ttools : [ {\r\n");
      out.write("\t\t\t\t\t\ticonCls : 'icon-mini-refresh',\r\n");
      out.write("\t\t\t\t\t\thandler : function() {\r\n");
      out.write("\t\t\t\t\t\t\trefreshTab(text);\r\n");
      out.write("\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t} ]\r\n");
      out.write("\t\t\t\t});\r\n");
      out.write("\t\t\t} else {\r\n");
      out.write("\t\t\t\tcenterTabs.tabs('add', {\r\n");
      out.write("\t\t\t\t\ttitle : text,\r\n");
      out.write("\t\t\t\t\tclosable : true,\r\n");
      out.write("\t\t\t\t\ticonCls : iconCls,\r\n");
      out.write("\t\t\t\t\tcontent : '<iframe src=\"error/err.jsp\" frameborder=\"0\" style=\"border:0;width:100%;height:99.4%;\"></iframe>',\r\n");
      out.write("\t\t\t\t\ttools : [ {\r\n");
      out.write("\t\t\t\t\t\ticonCls : 'icon-mini-refresh',\r\n");
      out.write("\t\t\t\t\t\thandler : function() {\r\n");
      out.write("\t\t\t\t\t\t\trefreshTab(text);\r\n");
      out.write("\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t} ]\r\n");
      out.write("\t\t\t\t});\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t}\r\n");
      out.write("\t}\r\n");
      out.write("</script>\r\n");
      out.write("<div id=\"centerTabs\">\r\n");
      out.write("  <!-- <div title=\"公告版\" border=\"false\" href=\"layout/portal.jsp\" style=\"overflow: hidden;\"></div> --> \r\n");
      out.write("</div>\r\n");
      out.write("<div id=\"tabsMenu\" style=\"width: 120px;display:none;\">\r\n");
      out.write("\t<div type=\"refresh\">刷新</div>\r\n");
      out.write("\t<div class=\"menu-sep\"></div>\r\n");
      out.write("\t<div type=\"close\">关闭</div>\r\n");
      out.write("\t<div type=\"closeOther\">关闭其他</div>\r\n");
      out.write("\t<div type=\"closeAll\">关闭所有</div>\r\n");
      out.write("</div>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
