/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.84
 * Generated at: 2018-03-27 01:57:25 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.business.stockin;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.util.*;

public final class stockin_002dmain_002dadd_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");

	String basePath = request.getScheme() + "://" + request.getServerName() + ":" + request.getServerPort() + request.getContextPath();

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "/inc.jsp", out, false);
      out.write("\r\n");
      out.write("\t<style>\r\n");
      out.write("\t.huibd {\r\n");
      out.write("\t\tborder: 1px solid #000000;\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\ttd {\r\n");
      out.write("\t\twhite-space: nowrap;\r\n");
      out.write("\t\tfont-size: 12px;\r\n");
      out.write("\t\t}\r\n");
      out.write("    .comboxstock{\r\n");
      out.write("\t   width:470px;\r\n");
      out.write("\t   border:0px solid #cfcfcf;\r\n");
      out.write("\t   border-collapse: collapse;\r\n");
      out.write("\t   margin:0px;\r\n");
      out.write("\t   table-layout:fixed;\r\n");
      out.write("\t}\r\n");
      out.write("\t.comboxstock td{\r\n");
      out.write("\t   overflow:hidden;\r\n");
      out.write("\t}\r\n");
      out.write("\t</style>\r\n");
      out.write("<link rel=\"stylesheet\" href=\"");
      out.print(basePath);
      out.write("/main/include/css/button-usr.css\" type=\"text/css\"></link>\r\n");
      out.write("<script language=\"javascript\" type=\"text/javascript\" src=\"");
      out.print(basePath);
      out.write("/main/include/js/form_valid.js\"></script>\r\n");
      out.write("<script language=\"javascript\" type=\"text/javascript\" src=\"");
      out.print(basePath);
      out.write("/jslib/datepicker/WdatePicker.js\"></script>\r\n");
      out.write("<link rel=\"stylesheet\" href=\"");
      out.print(basePath);
      out.write("/main/css/tablelock.css\" mce_href=\"tablelock.css\" /> \r\n");
      out.write("<script type=\"text/javascript\" language=\"javascript\" src=\"");
      out.print(basePath);
      out.write("/main/js/tablelock.js\"></script> \r\n");
      out.write("<script type=\"text/javascript\" charset=\"utf-8\">\r\n");
      out.write("var myForm;\r\n");
      out.write("$(document).ready(function() {\r\n");
      out.write("\t\t//$.fn.TableLock({table:'stockinDetail_table',lockRow:0,lockColumn:0,width:'960px',height:'100%'});\r\n");
      out.write("\t$(\".tabs\").tabs({width:960});\r\n");
      out.write("\t$(\"#doReturn\").click(function(){\r\n");
      out.write("\t\t window.parent.window.closePayoutDialog();\r\n");
      out.write("\t\t});\r\n");
      out.write("\t\r\n");
      out.write("\t //入库明细表追加\r\n");
      out.write("\t $(\"#button_add_stockinDetail\").bind(\"click\", function(){\r\n");
      out.write("\t  \t   var tr =  $(\"#add_stockinDetail_table_template tr\").clone();\r\n");
      out.write("\t  \t  var keyid = sy.UUID();\r\n");
      out.write("\t  \t     tr.attr(\"id\",keyid);\r\n");
      out.write("\t \t     $(\"#add_stockinDetail_table\").append(tr);\r\n");
      out.write("\t \t  var articlename = tr.find(\"select[name*='articlename']\").eq(0);\r\n");
      out.write("\t \t      articlename.attr(\"class\",\"easyui-combobox\");\r\n");
      out.write("\t \t  var expiredate = tr.find(\"input[name*='expiredate']\").eq(0);\r\n");
      out.write("\t \t     expiredate.attr(\"class\",\"easyui-datebox\");\r\n");
      out.write("\t \t  var num = tr.find(\"input[name*='num']\").eq(0);\r\n");
      out.write("\t \t     num.attr(\"class\",\"easyui-numberbox\");\r\n");
      out.write("\t \t  var price = tr.find(\"input[name*='price']\").eq(0);\r\n");
      out.write("\t \t     price.attr(\"class\",\"easyui-numberbox\");\r\n");
      out.write("\t \t  var amount = tr.find(\"input[name*='amount']\").eq(0);\r\n");
      out.write("\t \t     amount.attr(\"class\",\"easyui-numberbox\");\r\n");
      out.write("\t\t  $.parser.parse(\"#\"+keyid);\r\n");
      out.write("\t \t  resetTrNumnew('add_stockinDetail_table');\r\n");
      out.write("\t });\r\n");
      out.write("\t //入库明细表删除\r\n");
      out.write("\t $(\"#button_del_stockinDetail\").bind(\"click\", function(){\r\n");
      out.write("\t  \t$(\"#add_stockinDetail_table\").find(\"input:checked\").parent().parent().remove(); \r\n");
      out.write("\t \t resetTrNumnew('add_stockinDetail_table');\r\n");
      out.write("\t });\r\n");
      out.write("\t \r\n");
      out.write("\t //提交Form\r\n");
      out.write("\t myForm = $('#myForm').form({\r\n");
      out.write("\t\t\turl : 'stockinAction!addMain.action',\r\n");
      out.write("\t\t\tsuccess : function(data) {\r\n");
      out.write("\t\t\t\tvar json = $.parseJSON(data);\r\n");
      out.write("\t\t\t\t$.messager.progress('close');\r\n");
      out.write("\t\t\t\t window.parent.window.closePayoutDialog();\r\n");
      out.write("\t\t\t\tif (json && json.success) {\r\n");
      out.write("\t\t\t\t\t//父窗口刷新datagrid,提示操作消息\r\n");
      out.write("\t\t\t\t\twindow.parent.window.datagrid.datagrid('reload');\r\n");
      out.write("\t\t\t\t\twindow.parent.window.messageshow('成功',json.msg);\r\n");
      out.write("\t\t\t\t} else {\r\n");
      out.write("\t\t\t\t    window.parent.window.messageshow('失败','操作失败!');\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t});\r\n");
      out.write("\t $(window.parent.document.getElementById(\"loading\")).fadeOut(\"slow\",function(){\r\n");
      out.write("         $(this).css(\"display\",\"none\");\r\n");
      out.write("      });\r\n");
      out.write("});\r\n");
      out.write("\r\n");
      out.write("    function resetTrNumnew(tableId) {\r\n");
      out.write("\t\t$tbody = $(\"#\"+tableId+\"\");\r\n");
      out.write("\t\t$tbody.find('>tr').each(function(i){\r\n");
      out.write("\t\t\t$(':input, select', this).each(function(){\r\n");
      out.write("\t\t\t\tvar $this = $(this), name = $this.attr('name'), val = $this.val();\r\n");
      out.write("\t\t\t\tvar comboname = $this.attr('comboname');\r\n");
      out.write("\t\t\t\tvar numberboxname = $this.attr('numberboxname');\r\n");
      out.write("\t\t\t\tif(name!=null){\r\n");
      out.write("\t\t\t\t\tif (name.indexOf(\"#index#\") >= 0){\r\n");
      out.write("\t\t\t\t\t\t$this.attr(\"name\",name.replace('#index#',i));\r\n");
      out.write("\t\t\t\t\t}else{\r\n");
      out.write("\t\t\t\t\t\tvar s = name.indexOf(\"[\");\r\n");
      out.write("\t\t\t\t\t\tvar e = name.indexOf(\"]\");\r\n");
      out.write("\t\t\t\t\t\tvar new_name = name.substring(s+1,e);\r\n");
      out.write("\t\t\t\t\t\t$this.attr(\"name\",name.replace(new_name,i));\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t\tif(comboname!=null){\r\n");
      out.write("\t\t\t\t\tif (comboname.indexOf(\"#index#\") >= 0){\r\n");
      out.write("\t\t\t\t\t\t$this.attr(\"comboname\",comboname.replace('#index#',i));\r\n");
      out.write("\t\t\t\t\t}else{\r\n");
      out.write("\t\t\t\t\t\tvar s = comboname.indexOf(\"[\");\r\n");
      out.write("\t\t\t\t\t\tvar e = comboname.indexOf(\"]\");\r\n");
      out.write("\t\t\t\t\t\tvar new_comboname = comboname.substring(s+1,e);\r\n");
      out.write("\t\t\t\t\t\t$this.attr(\"comboname\",comboname.replace(new_comboname,i));\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t\tif(numberboxname!=null){\r\n");
      out.write("\t\t\t\t\tif (numberboxname.indexOf(\"#index#\") >= 0){\r\n");
      out.write("\t\t\t\t\t\t$this.attr(\"numberboxname\",numberboxname.replace('#index#',i));\r\n");
      out.write("\t\t\t\t\t}else{\r\n");
      out.write("\t\t\t\t\t\tvar s = numberboxname.indexOf(\"[\");\r\n");
      out.write("\t\t\t\t\t\tvar e = numberboxname.indexOf(\"]\");\r\n");
      out.write("\t\t\t\t\t\tvar new_numberboxname = numberboxname.substring(s+1,e);\r\n");
      out.write("\t\t\t\t\t\t$this.attr(\"numberboxname\",numberboxname.replace(new_numberboxname,i));\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t});\r\n");
      out.write("\t\t});\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\t //初始化下标\r\n");
      out.write("\tfunction resetTrNum(tableId) {\r\n");
      out.write("\t\t$tbody = $(\"#\"+tableId+\"\");\r\n");
      out.write("\t\t$tbody.find('>tr').each(function(i){\r\n");
      out.write("\t\t\t$(':input, select', this).each(function(){\r\n");
      out.write("\t\t\t\tvar $this = $(this), name = $this.attr('name'), val = $this.val();\r\n");
      out.write("\t\t\t\tif(name!=null){\r\n");
      out.write("\t\t\t\t\tif (name.indexOf(\"#index#\") >= 0){\r\n");
      out.write("\t\t\t\t\t\t$this.attr(\"name\",name.replace('#index#',i));\r\n");
      out.write("\t\t\t\t\t}else{\r\n");
      out.write("\t\t\t\t\t\tvar s = name.indexOf(\"[\");\r\n");
      out.write("\t\t\t\t\t\tvar e = name.indexOf(\"]\");\r\n");
      out.write("\t\t\t\t\t\tvar new_name = name.substring(s+1,e);\r\n");
      out.write("\t\t\t\t\t\t$this.attr(\"name\",name.replace(new_name,i));\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t});\r\n");
      out.write("\t\t});\r\n");
      out.write("\t}\r\n");
      out.write("\r\n");
      out.write("\t//form提交\r\n");
      out.write(" \tfunction dosubmit(){\r\n");
      out.write("\t\tif($('#myForm').form('validate')){\r\n");
      out.write("\t\t  if (checkStockAgain()){\r\n");
      out.write("\t\t          if (totalamount<=0){\r\n");
      out.write("\t\t            $.messager.alert('提示', \"总计金额为零，请核查！\", 'warn');\r\n");
      out.write("\t                return;\r\n");
      out.write("\t\t          }\r\n");
      out.write("\t\t          $.messager.confirm('请确认','总计金额：'+totalamount+'，您确定提交吗？',function(r){   \r\n");
      out.write("\t\t\t\t    if (r){\r\n");
      out.write("\t\t\t\t       $.messager.progress({\r\n");
      out.write("\t\t\t\t\t\t\ttext : '数据保存中....',\r\n");
      out.write("\t\t\t\t\t\t\tinterval : 100\r\n");
      out.write("\t\t\t\t\t\t});\r\n");
      out.write("\t\t\t           myForm.submit();\r\n");
      out.write("\t\t\t        }\r\n");
      out.write("\t\t\t      });\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t}\r\n");
      out.write("   \t}\r\n");
      out.write("   \t\r\n");
      out.write("   \t //检查主键重复\r\n");
      out.write("   \t var totalamount = 0.0;\r\n");
      out.write("\tfunction checkStockAgain() {\r\n");
      out.write("\t    totalamount = 0.0;\r\n");
      out.write("\t\t$tbody = $(\"#add_stockinDetail_table\");\r\n");
      out.write("\t\tvar stockkeyinfo = \"\";\r\n");
      out.write("\t\tvar flag = true;\r\n");
      out.write("\t\tvar rows = $tbody.find('>tr');\r\n");
      out.write("\t\tfor (var i=0;i<rows.length;i++){\r\n");
      out.write("\t\t    var articleid = $(\"input[name*='.articleid']\", rows[i]).val();\r\n");
      out.write("\t\t    var serial = $(\"input[name*='.serial']\", rows[i]).val();\r\n");
      out.write("\t\t    var num = $(\"input[name*='.num']\", rows[i]).val();\r\n");
      out.write("\t\t    var price = $(\"input[name*='.price']\", rows[i]).val();\r\n");
      out.write("\t\t    totalamount += parseInt(num,10)*parseFloat(price,10);\r\n");
      out.write("\t\t    var key = articleid+\"|\"+serial;\r\n");
      out.write("\t\t    if (stockkeyinfo.indexOf(key)!=-1){\r\n");
      out.write("\t\t        var articlename = $(\"select[id*='.articlename']\", rows[i]).combobox(\"getText\");\r\n");
      out.write("\t\t        var againinf = \"第\"+(i+1)+\"行[\"+articlename+\"]批号[\"+serial+\"]与前面的存在重复!\";\r\n");
      out.write("\t\t\t    $.messager.alert('提示', againinf, 'warn');\r\n");
      out.write("\t\t\t    return false;\r\n");
      out.write("\t\t\t}else{\r\n");
      out.write("\t\t\t    stockkeyinfo = stockkeyinfo + \",\" + key;\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\treturn flag;\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\tfunction computeAmount(obj){\r\n");
      out.write("\t   var price = $(obj).parent().prev().find(\"input[name*='.price']\").eq(0).val();\r\n");
      out.write("\t   var num = $(obj).parent().prev().prev().find(\"input[name*='.num']\").eq(0).val();\r\n");
      out.write("\t   if (num!=null&&num!=\"\"&&price!=null&&price!=\"\")\r\n");
      out.write("\t      $(obj).val(parseInt(num,10)*parseFloat(price,10));\r\n");
      out.write("\t}\r\n");
      out.write("</script>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("        \r\n");
      out.write("        <div id=\"chk_idAll\">\r\n");
      out.write("            <form name=\"myForm\" id=\"myForm\" method=\"post\">\r\n");
      out.write("             <div>\r\n");
      out.write("              <table width=\"968px\">\r\n");
      out.write("                  <tr bgcolor=\"#CCE6D1\">\r\n");
      out.write("                    <td colspan=\"8\"   style=\"font-size:14px;text-align:center;\"><strong>采购入库单</strong></td>\r\n");
      out.write("                  </tr>\r\n");
      out.write("\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t    <td align=\"left\">供应商</td>\r\n");
      out.write("                    \t<td align=\"left\">\r\n");
      out.write("                    \t    <select id=\"supplierid\" name=\"supplierid\" type=\"text\"  class=\"easyui-combobox\" data-options=\"required:true,\r\n");
      out.write("\t\t \t\t\t\t\t\t       url:'supplierAction!combox.action',\r\n");
      out.write("\t\t\t\t\t\t\t\t      \t valueField:'supplierid',\r\n");
      out.write("\t\t\t\t\t\t\t\t         textField:'suppliername',\r\n");
      out.write("\t\t\t\t\t\t                editable:false\r\n");
      out.write("\t\t \t\t\t\t\t\t       \"  missingMessage=\"请填写供应商\"  style=\"width: 180px;\">\r\n");
      out.write("\t\t \t\t\t\t\t</select>\r\n");
      out.write("                    \t</td>\r\n");
      out.write("                    \t<td align=\"left\">仓库</td>\r\n");
      out.write("                    \t<td align=\"left\">\r\n");
      out.write("                    \t    <select id=\"depotid\" name=\"depotid\" type=\"text\"  class=\"easyui-combobox\" data-options=\"required:true,\r\n");
      out.write("\t\t \t\t\t\t\t\t       url:'depotAction!combox.action',\r\n");
      out.write("\t\t\t\t\t\t\t\t      \t valueField:'depotid',\r\n");
      out.write("\t\t\t\t\t\t\t\t         textField:'depotname',\r\n");
      out.write("\t\t\t\t\t\t                editable:false\r\n");
      out.write("\t\t \t\t\t\t\t\t       \"  missingMessage=\"请填写供仓库\"  style=\"width: 159px;\">\r\n");
      out.write("\t\t \t\t\t\t\t\t     </select>\r\n");
      out.write("                    \t</td>\r\n");
      out.write("                   \t \t<td align=\"left\">入库日期</td>\r\n");
      out.write("                    \t<td align=\"left\">\r\n");
      out.write("                    \t\t<input name=\"stockindate\" type=\"text\" class=\"easyui-datetimebox\" maxlength=\"\" data-options=\"required:true\" style=\"width:150px;\"/>\r\n");
      out.write("                    \t</td>\r\n");
      out.write("                   \t \t<td align=\"left\">备注</td>\r\n");
      out.write("                    \t<td align=\"left\">\r\n");
      out.write("                    \t\t<input name=\"meno\" type=\"text\" class=\"easyui-validatebox\" maxlength=\"\" data-options=\"\" style=\"width:285px;\"/>\r\n");
      out.write("                    \t</td>\r\n");
      out.write("\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t   </table>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t<div class=\"tabs\">\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t <div title=\"入库明细表\">\r\n");
      out.write("\t\t\t\t  <table >\r\n");
      out.write("                  <tr bgcolor=\"#CCE6D1\">\r\n");
      out.write("                    <td align=\"left\" ><strong>&nbsp;&nbsp;入库明细表&nbsp;&nbsp;</strong>\r\n");
      out.write("                    <input type=\"button\" id=\"button_add_stockinDetail\" class=\" wd1 btn\" value=\"添加\"/>\r\n");
      out.write("                    <input type=\"button\" id=\"button_del_stockinDetail\" class=\" wd1 btn\" value=\"删除\"/>\r\n");
      out.write("                    </td>\r\n");
      out.write("                  </tr>\r\n");
      out.write("                 \r\n");
      out.write("                   <tr>\r\n");
      out.write("                    <td  align=\"left\">\r\n");
      out.write("                    <table border=\"0\" cellpadding=\"2\" cellspacing=\"0\" id=\"stockinDetail_table\">\r\n");
      out.write("                        <tr bgcolor=\"#E6E6E6\">\r\n");
      out.write("                              <td align=\"center\" bgcolor=\"#EEEEEE\">序号</td>\r\n");
      out.write("\t\t\t\t\t\t\t  <td align=\"center\" bgcolor=\"#EEEEEE\">品种</td>\r\n");
      out.write("\t\t\t\t\t\t\t  <td align=\"center\" bgcolor=\"#EEEEEE\">编码</td>\r\n");
      out.write("\t\t\t\t\t\t\t  <td align=\"center\" bgcolor=\"#EEEEEE\">规格</td>\r\n");
      out.write("\t\t\t\t\t\t\t  <td align=\"center\" bgcolor=\"#EEEEEE\">厂家</td>\r\n");
      out.write("\t\t\t\t\t\t\t  <td align=\"center\" bgcolor=\"#EEEEEE\">单位</td>\r\n");
      out.write("\t\t\t\t\t\t\t  <td align=\"center\" bgcolor=\"#EEEEEE\">批号</td>\r\n");
      out.write("\t\t\t\t\t\t\t  <td align=\"center\" bgcolor=\"#EEEEEE\">有效期</td>\r\n");
      out.write("\t\t\t\t\t\t\t  <td align=\"center\" bgcolor=\"#EEEEEE\">数量</td>\r\n");
      out.write("\t\t\t\t\t\t\t  <td align=\"center\" bgcolor=\"#EEEEEE\">进价</td>\r\n");
      out.write("\t\t\t\t\t\t\t  <td align=\"center\" bgcolor=\"#EEEEEE\">金额</td>\r\n");
      out.write("                        </tr>\r\n");
      out.write("                        <tr>\r\n");
      out.write("                          <td align=\"center\" colspan=\"20\" height=\"1\" bgcolor=\"#D8D8D8\"></td>\r\n");
      out.write("                        </tr>\r\n");
      out.write("                        <tbody id=\"add_stockinDetail_table\">\r\n");
      out.write("\t                        <tr>\r\n");
      out.write("\t                          <td align=\"center\"><input type=\"checkbox\" name=\"ck\"/></td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td align=\"left\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<select id=\"stockinDetailList[0].articlename\" name=\"stockinDetailList[0].articlename\" type=\"text\"  class=\"easyui-combobox\" data-options=\"required:true,\r\n");
      out.write("\t\t \t\t\t\t\t\t        url:'articleAction!getArticleForStockIn.action',\r\n");
      out.write("\t\t\t\t\t\t\t\t      \tvalueField:'articleid',\r\n");
      out.write("\t\t\t\t\t\t\t\t        textField:'articlename',\r\n");
      out.write("\t\t\t\t\t\t                panelHeight:90,\r\n");
      out.write("\t\t\t\t\t\t                panelWidth:500,\r\n");
      out.write("\t\t\t\t\t\t                filter: function(q, row){\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\tvar opts = $(this).combobox('options');\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\treturn row[opts.textField].indexOf(q)!=-1||row['articlealias'].indexOf(q)!=-1;\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t},\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tformatter:function(row){\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t   var factoryname = row.factory;\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t   if (row.factory.length>7) factoryname = row.factory.substring(0,7);\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t   var articlespec = row.articlespec;\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t   if (row.articlespec.length>12) articlespec = row.articlespec.substring(0,12);\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t   return '<table  class=comboxstock ><tr><td >'+row.articlename+'</td><td width=110px;>'+articlespec+'</td><td width=100px;>'+factoryname+'</td><td width=40px;>'+row.unitname+'</td></tr></table>';\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t},\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tonSelect: function(rec){ \r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t     var articleid = $(this).parent().next().children('input').eq(0).val(rec.articleid);\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t     var spec = $(this).parent().next().next().children('input').eq(0).val(rec.articlespec);\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t     var factory = $(this).parent().next().next().next().children('input').eq(0).val(rec.factory);\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t     var unitname = $(this).parent().next().next().next().next().children('input').eq(0).val(rec.unitname);\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t     //var serial = $(this).parent().next().next().next().next().children('input').eq(0).focus();\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t}\r\n");
      out.write("\t\t \t\t\t\t\t\t       \"  missingMessage=\"请填写品种\"  style=\"width:140px;\" >\r\n");
      out.write("\t\t \t\t\t\t\t       </select>\r\n");
      out.write("\t\t\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t <td align=\"left\"  >\r\n");
      out.write("\t\t\t\t\t\t\t\t   <input type=\"text\" name=\"stockinDetailList[0].articleid\" style=\"width:80px;\" class=\"easyui-validatebox\"/>\r\n");
      out.write("\t\t\t\t\t\t\t\t  </td>\r\n");
      out.write("\t\t\t\t\t\t\t\t <td align=\"left\"  >\r\n");
      out.write("\t\t\t\t\t\t\t\t   <input type=\"text\" disabled=\"disabled\" style=\"width:80px;\" class=\"easyui-validatebox\"/>\r\n");
      out.write("\t\t\t\t\t\t\t\t  </td>\r\n");
      out.write("\t\t\t\t\t\t\t\t  <td align=\"left\" >\r\n");
      out.write("\t\t\t\t\t\t\t\t    <input type=\"text\" disabled=\"disabled\" style=\"width:90px;\" class=\"easyui-validatebox\"/>\r\n");
      out.write("\t\t\t\t\t\t\t\t  </td>\r\n");
      out.write("\t\t\t\t\t\t\t\t  <td align=\"left\" >\r\n");
      out.write("\t\t\t\t\t\t\t\t    <input type=\"text\" disabled=\"disabled\" style=\"width:50px;\" class=\"easyui-validatebox\"/>\r\n");
      out.write("\t\t\t\t\t\t\t\t  </td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td align=\"left\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<input name=\"stockinDetailList[0].serial\" maxlength=\"20\" type=\"text\" \r\n");
      out.write("\t\t\t\t\t\t\t\t\t  class=\"easyui-validatebox\" data-options=\"required:true\" style=\"width:75px;\" >\r\n");
      out.write("\t\t\t\t\t\t\t    </td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td align=\"left\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<input name=\"stockinDetailList[0].expiredate\" maxlength=\"\" type=\"text\" class=\"easyui-datebox\" \r\n");
      out.write("\t\t\t\t\t\t\t\t\t data-options=\"required:true\" style=\"width:90px;\" >\r\n");
      out.write("\t\t\t\t\t\t\t\t </td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td align=\"left\"><input name=\"stockinDetailList[0].num\" maxlength=\"\" data-options=\"required:true,precision:0\" type=\"text\" \r\n");
      out.write("\t\t\t\t\t\t\t\tclass=\"easyui-numberbox\" style=\"width:70px;\" >\r\n");
      out.write("\t\t\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td align=\"left\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<input name=\"stockinDetailList[0].price\" maxlength=\"\" data-options=\"required:true,precision:2\"\r\n");
      out.write("\t\t\t\t\t\t\t\ttype=\"text\" class=\"easyui-numberbox\" style=\"width:80px;\" >\r\n");
      out.write("\t\t\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td align=\"left\"><input name=\"stockinDetailList[0].amount\" maxlength=\"\" type=\"text\" onclick=\"computeAmount(this)\" readonly=\"readonly\"\r\n");
      out.write("\t\t\t\t\t\t\t\t  data-options=\"precision:2\" style=\"width:80px;\" >\r\n");
      out.write("\t\t\t\t\t\t\t\t</td>\r\n");
      out.write("\t                        </tr>\r\n");
      out.write("                       </tbody>\r\n");
      out.write("                      </table>\r\n");
      out.write("                    </td>\r\n");
      out.write("                  </tr>\r\n");
      out.write("             \t </table> \r\n");
      out.write("\t\t\t  </div>\r\n");
      out.write("\t   </div>\r\n");
      out.write("\t\t\t<div align=\"center\">\r\n");
      out.write("\t\t\t\t<table>\r\n");
      out.write("                  <tr>\r\n");
      out.write("                    <td height=\"50\" colspan=\"8\"  align=\"center\">\r\n");
      out.write("                        <input value=\" 关 闭 \" type=\"button\" id=\"doReturn\"/>\r\n");
      out.write("                      \t<input value=\" 提 交 \" type=\"button\" onClick=\"dosubmit();\"  />\r\n");
      out.write("                    </td>\r\n");
      out.write("                  </tr>\r\n");
      out.write("              </table>\r\n");
      out.write("\t\t    </div>\t\r\n");
      out.write(" \t\t </form>\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("<table style=\"display:none\">\r\n");
      out.write("       <tbody id=\"add_stockinDetail_table_template\">\r\n");
      out.write("          <tr>\r\n");
      out.write("             <td align=\"center\"><input type=\"checkbox\" name=\"ck\"/></td>\r\n");
      out.write("\t\t\t\t  <td align=\"left\">\r\n");
      out.write("\t\t\t\t       <select id=\"stockinDetailList[#index#].articlename\" name=\"stockinDetailList[#index#].articlename\"    data-options=\"required:true,\r\n");
      out.write("\t\t \t\t\t\t\t\t        //data:article_combox_data,\r\n");
      out.write("\t\t \t\t\t\t\t\t        url:'articleAction!getArticleForStockIn.action',\r\n");
      out.write("\t\t\t\t\t\t\t\t      \tvalueField:'articleid',\r\n");
      out.write("\t\t\t\t\t\t\t\t        textField:'articlename',\r\n");
      out.write("\t\t\t\t\t\t                panelHeight:90,\r\n");
      out.write("\t\t\t\t\t\t                panelWidth:500,\r\n");
      out.write("\t\t\t\t\t\t                filter: function(q, row){\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\tvar opts = $(this).combobox('options');\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\treturn row[opts.textField].indexOf(q)!=-1||row['articlealias'].indexOf(q)!=-1;\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t},\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tformatter:function(row){\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t   var factoryname = row.factory;\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t   if (row.factory.length>7) factoryname = row.factory.substring(0,7);\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t   var articlespec = row.articlespec;\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t   if (row.articlespec.length>12) articlespec = row.articlespec.substring(0,12);\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t   return '<table  class=comboxstock ><tr><td >'+row.articlename+'</td><td width=110px;>'+articlespec+'</td><td width=100px;>'+factoryname+'</td><td width=40px;>'+row.unitname+'</td></tr></table>';\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t},\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tonSelect: function(rec){ \r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t     var articleid = $(this).parent().next().children('input').eq(0).val(rec.articleid);\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t     var spec = $(this).parent().next().next().children('input').eq(0).val(rec.articlespec);\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t     var factory = $(this).parent().next().next().next().children('input').eq(0).val(rec.factory);\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t     var unitname = $(this).parent().next().next().next().next().children('input').eq(0).val(rec.unitname);\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t     //var serial = $(this).parent().next().next().next().next().children('input').eq(0).focus();\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t}\r\n");
      out.write("\t\t \t\t\t\t \"   missingMessage=\"请填写品种\"  style=\"width:140px;\">\r\n");
      out.write("\t\t \t\t\t</select>\r\n");
      out.write("\t\t\t\t  </td>\r\n");
      out.write("\t\t\t\t  <td align=\"left\"  >\r\n");
      out.write("\t\t\t\t   <input type=\"text\" name=\"stockinDetailList[#index#].articleid\" style=\"width:80px;\" class=\"easyui-validatebox\"/>\r\n");
      out.write("\t\t\t\t  </td>\r\n");
      out.write("\t\t\t\t <td align=\"left\"  >\r\n");
      out.write("\t\t\t\t   <input type=\"text\" disabled=\"disabled\" style=\"width:80px;\" class=\"easyui-validatebox\"/>\r\n");
      out.write("\t\t\t\t  </td>\r\n");
      out.write("\t\t\t\t  <td align=\"left\" >\r\n");
      out.write("\t\t\t\t    <input type=\"text\" disabled=\"disabled\" style=\"width:90px;\" class=\"easyui-validatebox\"/>\r\n");
      out.write("\t\t\t\t  </td>\r\n");
      out.write("\t\t\t\t  <td align=\"left\" >\r\n");
      out.write("\t\t\t\t    <input type=\"text\" disabled=\"disabled\" style=\"width:50px;\" class=\"easyui-validatebox\"/>\r\n");
      out.write("\t\t\t\t  </td>\r\n");
      out.write("\t\t\t\t  <td align=\"left\"><input name=\"stockinDetailList[#index#].serial\" maxlength=\"20\" data-options=\"required:true\" class=\"easyui-validatebox\" type=\"text\" style=\"width:75px;\"></td>\r\n");
      out.write("\t\t\t\t  <td align=\"left\"><input name=\"stockinDetailList[#index#].expiredate\" maxlength=\"\" data-options=\"required:true\" type=\"text\" style=\"width:90px;\"></td>\r\n");
      out.write("\t\t\t\t  <td align=\"left\"><input name=\"stockinDetailList[#index#].num\" maxlength=\"\" data-options=\"required:true,precision:0\" type=\"text\" style=\"width:70px;\"></td>\r\n");
      out.write("\t\t\t\t  <td align=\"left\"><input name=\"stockinDetailList[#index#].price\" maxlength=\"\" data-options=\"required:true,precision:2\" type=\"text\" style=\"width:80px;\"></td>\r\n");
      out.write("\t\t\t\t  <td align=\"left\"><input name=\"stockinDetailList[#index#].amount\" maxlength=\"\" data-options=\"required:true\"  onclick=\"computeAmount(this)\" readonly=\"readonly\" type=\"text\" style=\"width:80px;\"></td>\r\n");
      out.write("           </tr>\r\n");
      out.write("      </tbody>\r\n");
      out.write("</table>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
