/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.84
 * Generated at: 2018-03-27 01:58:40 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.business.stockin;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.util.*;

public final class view_002dstockin_002dtotal_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "/inc.jsp", out, false);
      out.write("\r\n");
      out.write("<script type=\"text/javascript\" charset=\"utf-8\">\r\n");
      out.write("    var searchForm;\r\n");
      out.write("    $(function() {\r\n");
      out.write("        searchForm = $('#searchForm').form();\r\n");
      out.write("        $(\"#begindate\").datebox(\"setValue\",(sy.getMonthBeginDate()).format('yyyy-MM-dd 00:00:00'));\r\n");
      out.write("        $(\"#enddate\").datebox(\"setValue\",(sy.getMonthEndDate()).format('yyyy-MM-dd 23:59:59'));\r\n");
      out.write("    });\r\n");
      out.write("    function   _search() {\r\n");
      out.write("      if  ($('#searchForm').form('validate')){\r\n");
      out.write("\t       var  querystring = sy.jsonToUrlParam(searchForm);\r\n");
      out.write("\t       document.getElementById(\"iframe\").src = \"stockinAction!viewStockinTotalData.action?\"+querystring;\r\n");
      out.write("\t    }\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\tfunction cleanSearch() {\r\n");
      out.write("\t\tsearchForm.find('input').val('');\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("</script>\r\n");
      out.write("</head>\r\n");
      out.write("<body class=\"easyui-layout\">\r\n");
      out.write("\t<div region=\"north\" border=\"false\" title=\"查询条件\"  style=\"height: 60px;overflow: hidden;\" align=\"left\">\r\n");
      out.write("\t\t<form id=\"searchForm\" method=\"post\" target=\"iframe\">\r\n");
      out.write("\t\t\t<table class=\"tableForm datagrid-toolbar\" style=\"width: 100%;height: 100%;\">\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t    <td width=\"45px\">供应商</td>\r\n");
      out.write("\t\t\t\t\t<td>\r\n");
      out.write("\t\t\t\t\t   <select id=\"supplierid\" name=\"reportQueryForm.supplierid\" type=\"text\"  class=\"easyui-combobox\" data-options=\"\r\n");
      out.write("\t\t \t\t\t\t\t\t       url:'supplierAction!combox.action',\r\n");
      out.write("\t\t\t\t\t\t\t\t      \t valueField:'supplierid',\r\n");
      out.write("\t\t\t\t\t\t\t\t         textField:'suppliername',\r\n");
      out.write("\t\t\t\t\t\t                editable:false\r\n");
      out.write("\t\t \t\t\t\t\t\t       \"  missingMessage=\"请填写供应商\"  style=\"width: 120px;\">\r\n");
      out.write("\t\t \t\t\t\t\t\t     </select>\r\n");
      out.write("\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t<td width=\"30px\">仓库</td>\r\n");
      out.write("\t\t\t\t\t<td>\r\n");
      out.write("\t\t\t\t\t   <select id=\"depotid\" name=\"reportQueryForm.depotid\" type=\"text\"  class=\"easyui-combobox\" data-options=\"\r\n");
      out.write("\t\t \t\t\t\t\t\t       url:'depotAction!combox.action',\r\n");
      out.write("\t\t\t\t\t\t\t\t      \t valueField:'depotid',\r\n");
      out.write("\t\t\t\t\t\t\t\t         textField:'depotname',\r\n");
      out.write("\t\t\t\t\t\t                editable:false\r\n");
      out.write("\t\t \t\t\t\t\t\t       \"    style=\"width: 100px;\">\r\n");
      out.write("\t\t \t\t\t\t</select>\r\n");
      out.write("\t\t \t\t    </td>\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t<td width=\"60px\" style=\"display: none;\">是否付款</td>\r\n");
      out.write("\t\t\t\t\t<td style=\"display: none;\">\r\n");
      out.write("\t\t\t\t\t  <select id=\"ispayed\" name=\"reportQueryForm.ispayed\" class=\"easyui-combobox\" data-options=\"\r\n");
      out.write("\t\t \t\t\t\t\t\t        panelHeight:45,\r\n");
      out.write("\t\t \t\t\t\t\t\t        url : 'dictParamAction!dictCombobox.action?paramLevel=004',\r\n");
      out.write("\t\t\t\t\t\t                valueField : 'paramValue',\r\n");
      out.write("\t\t\t\t\t\t                textField : 'paramName',\r\n");
      out.write("\t\t\t\t\t\t                editable:false\r\n");
      out.write("\t\t \t\t\t\t\t\t       \" missingMessage=\"请填写是否付款\"  style=\"width: 50px;\">\r\n");
      out.write("\t\t \t\t\t  </select>\r\n");
      out.write("\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t<td>入库日期</td>\r\n");
      out.write("\t\t\t\t\t<td>\r\n");
      out.write("\t\t\t\t\t  <input id=\"begindate\" name=\"reportQueryForm.begindate\" data-options=\"required:true\" style=\"width:117px;\" class=\"easyui-datetimebox\"/>\r\n");
      out.write("\t\t\t\t\t  <input id=\"enddate\" name=\"reportQueryForm.enddate\" data-options=\"required:true\" style=\"width:117px;\" class=\"easyui-datetimebox\"/>\r\n");
      out.write("\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t<td width=\"70px\">入库操作人</td>\r\n");
      out.write("\t\t\t\t\t<td>\r\n");
      out.write("\t\t\t\t\t<select id=\"crtuser\" name=\"reportQueryForm.crtuser\" type=\"text\"  class=\"easyui-combobox\" data-options=\"\r\n");
      out.write("\t\t \t\t\t\t\t\t       url:'userAction!combox.action',\r\n");
      out.write("\t\t\t\t\t\t\t\t      \t valueField:'cid',\r\n");
      out.write("\t\t\t\t\t\t\t\t         textField:'realname',\r\n");
      out.write("\t\t\t\t\t\t                editable:false\r\n");
      out.write("\t\t \t\t\t\t\t\t       \"  missingMessage=\"请填写入库操作人\"  style=\"width: 80px;\">\r\n");
      out.write("\t\t \t\t\t\t\t\t     </select>\r\n");
      out.write("\t\t \t\t    </td>\r\n");
      out.write("\t\t\t        <td><a href=\"javascript:void(0);\" class=\"easyui-linkbutton\" onclick=\"_search();\">查询</a><a href=\"javascript:void(0);\" class=\"easyui-linkbutton\" onclick=\"cleanSearch();\">取消</a></td>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t</table>\r\n");
      out.write("\t\t</form>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<div region=\"center\" border=\"false\" >\r\n");
      out.write("\t\t<iframe name=\"iframe\" id=\"iframe\"  src=\"\"  scrolling=\"auto\" frameborder=\"0\" style=\"width:100%;height:99%;\">\r\n");
      out.write("        </iframe>\r\n");
      out.write("\t</div>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
