/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.84
 * Generated at: 2018-03-28 08:56:09 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.business.sale;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.util.*;

public final class sale_002dmain_002dadd_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");

	String basePath = request.getScheme() + "://" + request.getServerName() + ":" + request.getServerPort() + request.getContextPath();

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "/inc.jsp", out, false);
      out.write("\r\n");
      out.write("\t<style>\r\n");
      out.write("\t.huibd {\r\n");
      out.write("\t\tborder: 1px solid #000000;\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\ttd {\r\n");
      out.write("\t\twhite-space: nowrap;\r\n");
      out.write("\t\tfont-size: 12px;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t.comboxstock{\r\n");
      out.write("\t   width:610px;\r\n");
      out.write("\t   border:0px solid #cfcfcf;\r\n");
      out.write("\t   border-collapse: collapse;\r\n");
      out.write("\t   margin:0px;\r\n");
      out.write("\t   table-layout:fixed;\r\n");
      out.write("\t}\r\n");
      out.write("\t.comboxstock td{\r\n");
      out.write("\t   overflow:hidden;\r\n");
      out.write("\t}\r\n");
      out.write("\t</style>\r\n");
      out.write("<link rel=\"stylesheet\" href=\"");
      out.print(basePath);
      out.write("/main/include/css/button-usr.css\" type=\"text/css\"></link>\r\n");
      out.write("<script language=\"javascript\" type=\"text/javascript\" src=\"");
      out.print(basePath);
      out.write("/main/include/js/form_valid.js\"></script>\r\n");
      out.write("<script language=\"javascript\" type=\"text/javascript\" src=\"");
      out.print(basePath);
      out.write("/jslib/datepicker/WdatePicker.js\"></script>\r\n");
      out.write("<link rel=\"stylesheet\" href=\"");
      out.print(basePath);
      out.write("/main/css/tablelock.css\" mce_href=\"tablelock.css\" /> \r\n");
      out.write("<script type=\"text/javascript\" language=\"javascript\" src=\"");
      out.print(basePath);
      out.write("/main/js/tablelock.js\"></script> \r\n");
      out.write("<script type=\"text/javascript\" charset=\"utf-8\">\r\n");
      out.write("var myForm;\r\n");
      out.write("$(document).ready(function() {\r\n");
      out.write("\t\t//$.fn.TableLock({table:'saleDetail_table',lockRow:0,lockColumn:0,width:'960px',height:'100%'});\r\n");
      out.write("\t\r\n");
      out.write("\t$(\".tabs\").tabs({width:1000});\r\n");
      out.write("\t$(\"#doReturn\").click(function(){\r\n");
      out.write("\t\t window.parent.window.closePayoutDialog();\r\n");
      out.write("\t\t});\r\n");
      out.write("\t\r\n");
      out.write("\t //销售单明细追加\r\n");
      out.write("\t $(\"#button_add_saleDetail\").bind(\"click\", function(){\r\n");
      out.write("\t \t  var tr =  $(\"#add_saleDetail_table_template tr\").clone();\r\n");
      out.write("\t  \t  var keyid = sy.UUID();\r\n");
      out.write("\t  \t     tr.attr(\"id\",keyid);\r\n");
      out.write("\t \t     $(\"#add_saleDetail_table\").append(tr);\r\n");
      out.write("\t \t  var articlename = tr.find(\"select[name*='.articlename']\").eq(0);\r\n");
      out.write("\t \t      articlename.attr(\"class\",\"easyui-combobox\");\r\n");
      out.write("\t \t  var saleprice = tr.find(\"input[name*='.saleprice']\").eq(0);\r\n");
      out.write("\t \t     saleprice.attr(\"class\",\"easyui-numberbox\");\r\n");
      out.write("\t \t  var num = tr.find(\"input[name*='.num']\").eq(0);\r\n");
      out.write("\t \t     num.attr(\"class\",\"easyui-numberbox\");\r\n");
      out.write("\t \t  //var amount = tr.find(\"input[name*='.amount']\").eq(0);\r\n");
      out.write("\t \t     //amount.attr(\"class\",\"easyui-numberbox\");\r\n");
      out.write("\t\t  $.parser.parse(\"#\"+keyid);\r\n");
      out.write("\t \t  resetTrNumnew('add_saleDetail_table');\r\n");
      out.write("\t });\r\n");
      out.write("\t //销售单明细删除\r\n");
      out.write("\t $(\"#button_del_saleDetail\").bind(\"click\", function(){\r\n");
      out.write("\t  \t$(\"#add_saleDetail_table\").find(\"input:checked\").parent().parent().remove(); \r\n");
      out.write("\t \t resetTrNumnew('add_saleDetail_table');\r\n");
      out.write("\t });\r\n");
      out.write("\t \r\n");
      out.write("\t //提交Form\r\n");
      out.write("\t myForm = $('#myForm').form({\r\n");
      out.write("\t\t\turl : 'saleAction!addMain.action',\r\n");
      out.write("\t\t\tsuccess : function(data) {\r\n");
      out.write("\t\t\t\talert(data);\r\n");
      out.write("\t\t\t\tvar json = $.parseJSON(data);\r\n");
      out.write("\t\t\t\t$.messager.progress('close');\r\n");
      out.write("\t\t\t\t window.parent.window.closePayoutDialog();\r\n");
      out.write("\t\t\t\tif (json && json.success) {\r\n");
      out.write("\t\t\t\t\t//父窗口刷新datagrid,提示操作消息\r\n");
      out.write("\t\t\t\t\twindow.parent.window.datagrid.datagrid('reload');\r\n");
      out.write("\t\t\t\t\twindow.parent.window.messageshow('成功',json.msg);\r\n");
      out.write("\t\t\t\t} else {\r\n");
      out.write("\t\t\t\t    window.parent.window.messageshow('失败','操作失败!'+json.msg);\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t});\r\n");
      out.write("\t$(window.parent.document.getElementById(\"loading\")).fadeOut(\"slow\",function(){\r\n");
      out.write("         $(this).css(\"display\",\"none\");\r\n");
      out.write("    });\r\n");
      out.write("});\r\n");
      out.write("\r\n");
      out.write("  function resetTrNumnew(tableId) {\r\n");
      out.write("\t\t$tbody = $(\"#\"+tableId+\"\");\r\n");
      out.write("\t\t$tbody.find('>tr').each(function(i){\r\n");
      out.write("\t\t\t$(':input, select', this).each(function(){\r\n");
      out.write("\t\t\t\tvar $this = $(this), name = $this.attr('name'), val = $this.val();\r\n");
      out.write("\t\t\t\tvar comboname = $this.attr('comboname');\r\n");
      out.write("\t\t\t\tvar numberboxname = $this.attr('numberboxname');\r\n");
      out.write("\t\t\t\tif(name!=null){\r\n");
      out.write("\t\t\t\t\tif (name.indexOf(\"#index#\") >= 0){\r\n");
      out.write("\t\t\t\t\t\t$this.attr(\"name\",name.replace('#index#',i));\r\n");
      out.write("\t\t\t\t\t}else{\r\n");
      out.write("\t\t\t\t\t\tvar s = name.indexOf(\"[\");\r\n");
      out.write("\t\t\t\t\t\tvar e = name.indexOf(\"]\");\r\n");
      out.write("\t\t\t\t\t\tvar new_name = name.substring(s+1,e);\r\n");
      out.write("\t\t\t\t\t\t$this.attr(\"name\",name.replace(new_name,i));\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t\tif(comboname!=null){\r\n");
      out.write("\t\t\t\t\tif (comboname.indexOf(\"#index#\") >= 0){\r\n");
      out.write("\t\t\t\t\t\t$this.attr(\"comboname\",comboname.replace('#index#',i));\r\n");
      out.write("\t\t\t\t\t}else{\r\n");
      out.write("\t\t\t\t\t\tvar s = comboname.indexOf(\"[\");\r\n");
      out.write("\t\t\t\t\t\tvar e = comboname.indexOf(\"]\");\r\n");
      out.write("\t\t\t\t\t\tvar new_comboname = comboname.substring(s+1,e);\r\n");
      out.write("\t\t\t\t\t\t$this.attr(\"comboname\",comboname.replace(new_comboname,i));\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t\tif(numberboxname!=null){\r\n");
      out.write("\t\t\t\t\tif (numberboxname.indexOf(\"#index#\") >= 0){\r\n");
      out.write("\t\t\t\t\t\t$this.attr(\"numberboxname\",numberboxname.replace('#index#',i));\r\n");
      out.write("\t\t\t\t\t}else{\r\n");
      out.write("\t\t\t\t\t\tvar s = numberboxname.indexOf(\"[\");\r\n");
      out.write("\t\t\t\t\t\tvar e = numberboxname.indexOf(\"]\");\r\n");
      out.write("\t\t\t\t\t\tvar new_numberboxname = numberboxname.substring(s+1,e);\r\n");
      out.write("\t\t\t\t\t\t$this.attr(\"numberboxname\",numberboxname.replace(new_numberboxname,i));\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t});\r\n");
      out.write("\t\t});\r\n");
      out.write("\t}\r\n");
      out.write("\t //初始化下标\r\n");
      out.write("\tfunction resetTrNum(tableId) {\r\n");
      out.write("\t\t$tbody = $(\"#\"+tableId+\"\");\r\n");
      out.write("\t\t$tbody.find('>tr').each(function(i){\r\n");
      out.write("\t\t\t$(':input, select', this).each(function(){\r\n");
      out.write("\t\t\t\tvar $this = $(this), name = $this.attr('name'), val = $this.val();\r\n");
      out.write("\t\t\t\tif(name!=null){\r\n");
      out.write("\t\t\t\t\tif (name.indexOf(\"#index#\") >= 0){\r\n");
      out.write("\t\t\t\t\t\t$this.attr(\"name\",name.replace('#index#',i));\r\n");
      out.write("\t\t\t\t\t}else{\r\n");
      out.write("\t\t\t\t\t\tvar s = name.indexOf(\"[\");\r\n");
      out.write("\t\t\t\t\t\tvar e = name.indexOf(\"]\");\r\n");
      out.write("\t\t\t\t\t\tvar new_name = name.substring(s+1,e);\r\n");
      out.write("\t\t\t\t\t\t$this.attr(\"name\",name.replace(new_name,i));\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t});\r\n");
      out.write("\t\t});\r\n");
      out.write("\t}\r\n");
      out.write("\r\n");
      out.write("\t//form提交\r\n");
      out.write(" \tfunction dosubmit(){\r\n");
      out.write("\t\tif($('#myForm').form('validate')){\r\n");
      out.write("\t\t   if (checkStockAgain()){\r\n");
      out.write("\t\t      if (totalamount<=0){\r\n");
      out.write("\t\t            $.messager.alert('提示', \"总计金额为零，请核查！\", 'warn');\r\n");
      out.write("\t                return;\r\n");
      out.write("\t\t         }\r\n");
      out.write("\t\t      $.messager.confirm('请确认','总计金额：'+totalamount+'，您确定提交吗？',function(r){   \r\n");
      out.write("\t\t\t\t    if (r){  \r\n");
      out.write("\t\t\t\t        $.messager.progress({\r\n");
      out.write("\t\t\t\t\t\t\ttext : '数据保存中....',\r\n");
      out.write("\t\t\t\t\t\t\tinterval : 100\r\n");
      out.write("\t\t\t\t\t\t}); \r\n");
      out.write("\t\t\t\t        myForm.submit();\r\n");
      out.write("\t\t\t\t    }   \r\n");
      out.write("\t\t\t\t});\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t}\r\n");
      out.write("   \t}\r\n");
      out.write("   \t\r\n");
      out.write("   \t //检查主键重复\r\n");
      out.write("   \t var totalamount = 0.0;\r\n");
      out.write("\tfunction checkStockAgain() {\r\n");
      out.write("\t    totalamount = 0.0;\r\n");
      out.write("\t\t$tbody = $(\"#add_saleDetail_table\");\r\n");
      out.write("\t\tvar stockkeyinfo = \"\";\r\n");
      out.write("\t\tvar flag = true;\r\n");
      out.write("\t\tvar rows = $tbody.find('>tr');\r\n");
      out.write("\t\tfor (var i=0;i<rows.length;i++){\r\n");
      out.write("\t\t    var corrent = $(\"input[name*='.stockkey']\", rows[i]).val();\r\n");
      out.write("\t\t    var num = $(\"input[id*='.num']\", rows[i]).numberbox(\"getValue\");\r\n");
      out.write("\t\t    var saleprice = $(\"input[id*='.saleprice']\", rows[i]).numberbox(\"getValue\");\r\n");
      out.write("\t\t    totalamount += parseInt(num,10)*parseFloat(saleprice,10);\r\n");
      out.write("\t\t    var articlename = $(\"select[id*='.articlename']\", rows[i]).combobox(\"getText\");\r\n");
      out.write("\t\t    if (stockkeyinfo.indexOf(corrent)!=-1){\r\n");
      out.write("\t\t        var againinf = \"第\"+(i+1)+\"行[\"+articlename+\"]与前面的存在重复!\";\r\n");
      out.write("\t\t\t    $.messager.alert('提示', againinf, 'error');\r\n");
      out.write("\t\t\t    return false;\r\n");
      out.write("\t\t\t}else{\r\n");
      out.write("\t\t\t    stockkeyinfo = stockkeyinfo + \",\" + corrent;\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\treturn flag;\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\tfunction computeAmount(obj){\r\n");
      out.write("\t   var num = $(obj).parent().prev().find(\"input[id*='.num']\").eq(0).numberbox(\"getValue\");;\r\n");
      out.write("\t   var saleprice = $(obj).parent().prev().prev().find(\"input[id*='.saleprice']\").eq(0).numberbox(\"getValue\");\r\n");
      out.write("\t   if (num!=null&&num!=\"\"&&saleprice!=null&&saleprice!=\"\")\r\n");
      out.write("\t      $(obj).val(parseInt(num,10)*parseFloat(saleprice,10));\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\tfunction findLastInprice(obj){\r\n");
      out.write("\t  var articleid = $(obj).parent().parent().find(\"input[name*='.articleid']\").eq(0).val();\r\n");
      out.write("\t  var salepriceinput  = $(obj).parent().parent().find(\"input[id*='.saleprice']\").eq(0);\r\n");
      out.write("\t  var customerid = $(\"#customerid\").combobox(\"getValue\");\r\n");
      out.write("\t  if (customerid==null||customerid==\"\"){\r\n");
      out.write("\t     $.messager.alert('提示', \"请先选择客户！\", 'warn');\r\n");
      out.write("\t     return;\r\n");
      out.write("\t  }\r\n");
      out.write("\t  if (articleid==null||articleid==\"\"){\r\n");
      out.write("\t     $.messager.alert('提示', \"请先选择本行的品种！\", 'warn');\r\n");
      out.write("\t     return;\r\n");
      out.write("\t  }\r\n");
      out.write("      $.ajax({\r\n");
      out.write("\t\t\turl : 'customerPriceAction!getCustomerPrice.action',\r\n");
      out.write("\t\t\tdata : {\r\n");
      out.write("\t\t\t\tarticleid : articleid,\r\n");
      out.write("\t\t\t\tcustomerid : customerid\r\n");
      out.write("\t\t\t},\r\n");
      out.write("\t\t\tdataType : 'json',\r\n");
      out.write("\t\t\tcache : false,\r\n");
      out.write("\t\t\tasync:false,\r\n");
      out.write("\t\t\tsuccess : function(response) {\r\n");
      out.write("\t\t\t\tif(response.flag==1){\r\n");
      out.write("\t\t\t\t\t$.messager.alert('提示', \"该客户上次购买[\"+response.articlename+\"]<br>价格是：[\"+response.saleprice+\"]元！\", 'info');\r\n");
      out.write("\t\t\t\t\tsalepriceinput.numberbox('setValue',response.saleprice);\r\n");
      out.write("\t\t\t\t}else{\r\n");
      out.write("\t\t\t\t    $.messager.alert('提示', \"该客户还没有购买过此品种！\", 'info');\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t});\r\n");
      out.write("\t}\r\n");
      out.write("</script>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("        <div id=\"chk_idAll\">\r\n");
      out.write("            <form name=\"myForm\" id=\"myForm\" method=\"post\">\r\n");
      out.write("             <div>\r\n");
      out.write("              <table width=\"998px\">\r\n");
      out.write("                  <tr bgcolor=\"#CCE6D1\">\r\n");
      out.write("                    <td colspan=\"10\"  align=\"center\" style=\"font-size:14px;\"><strong>销售单</strong></td>\r\n");
      out.write("                  </tr>\r\n");
      out.write("\t\t\t\t\t<tr>\r\n");
      out.write("                   \t \t<td align=\"left\">销售客户</td>\r\n");
      out.write("                    \t<td align=\"left\">\r\n");
      out.write("                    \t    <select id=\"customerid\" name=\"customerid\" type=\"text\"  class=\"easyui-combobox\" data-options=\"required:true,\r\n");
      out.write("\t\t \t\t\t\t\t\t       url:'customerAction!combox.action',\r\n");
      out.write("\t\t\t\t\t\t\t\t      \t valueField:'customerid',\r\n");
      out.write("\t\t\t\t\t\t\t\t         textField:'customername',\r\n");
      out.write("\t\t\t\t\t\t                editable:false\r\n");
      out.write("\t\t \t\t\t\t\t\t       \"  missingMessage=\"请填写销售客户\"  style=\"width: 163px;\">\r\n");
      out.write("\t\t \t\t\t\t\t</select>\r\n");
      out.write("                    \t</td>\r\n");
      out.write("                   \t \t<td align=\"left\">销售日期</td>\r\n");
      out.write("                    \t<td align=\"left\">\r\n");
      out.write("                    \t\t<input name=\"saledate\" type=\"text\" style=\"width: 135px;\" class=\"easyui-datetimebox\" maxlength=\"\" data-options=\"required:true\"/>\r\n");
      out.write("                    \t</td>\r\n");
      out.write("                   \t \t<td align=\"left\">业务员</td>\r\n");
      out.write("                    \t<td align=\"left\">\r\n");
      out.write("                    \t    <select id=\"accountid\" name=\"accountid\" type=\"text\"  class=\"easyui-combobox\" data-options=\"required:true,\r\n");
      out.write("\t\t \t\t\t\t\t\t       url:'accounterAction!combox.action',\r\n");
      out.write("\t\t\t\t\t\t\t\t      \t valueField:'accountid',\r\n");
      out.write("\t\t\t\t\t\t\t\t         textField:'accountname',\r\n");
      out.write("\t\t\t\t\t\t                editable:false,\r\n");
      out.write("\t\t\t\t\t\t                onSelect: function(rec){ \r\n");
      out.write("\t\t\t\t\t\t                   $('#salerate').val(rec.rate);\r\n");
      out.write("\t\t\t\t\t\t                }\r\n");
      out.write("\t\t \t\t\t\t\t\t       \"  missingMessage=\"请填写业务员\"  style=\"width: 100px;\">\r\n");
      out.write("\t\t \t\t\t\t\t</select>\r\n");
      out.write("                    \t</td>\r\n");
      out.write("                    \t<td align=\"left\">提成比例</td>\r\n");
      out.write("                    \t<td align=\"left\">\r\n");
      out.write("                    \t\t<input id=\"salerate\" readonly=\"readonly\" style=\"width: 70px;\" name=\"salerate\" type=\"text\" class=\"easyui-validatebox\" maxlength=\"\" data-options=\"required:true\"/>\r\n");
      out.write("                    \t</td>\r\n");
      out.write("                    \t<td align=\"left\">备注</td>\r\n");
      out.write("                    \t<td align=\"left\">\r\n");
      out.write("                    \t\t<input style=\"width: 230px;\" name=\"meno\" type=\"text\" class=\"easyui-validatebox\" maxlength=\"100\" data-options=\"\"/>\r\n");
      out.write("                    \t</td>\r\n");
      out.write("\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t<tr>\r\n");
      out.write("                   \t \t\r\n");
      out.write("\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t   </table>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t<div class=\"tabs\">\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t <div title=\"销售单明细\">\r\n");
      out.write("\t\t\t\t  <table>\r\n");
      out.write("                  <tr bgcolor=\"#CCE6D1\">\r\n");
      out.write("                    <td align=\"left\" ><strong>&nbsp;&nbsp;销售单明细&nbsp;&nbsp;</strong>\r\n");
      out.write("                    <input type=\"button\" id=\"button_add_saleDetail\" class=\" wd1 btn\" value=\"添加\"/>\r\n");
      out.write("                    <input type=\"button\" id=\"button_del_saleDetail\" class=\" wd1 btn\" value=\"删除\"/>\r\n");
      out.write("                    </td>\r\n");
      out.write("                  </tr>\r\n");
      out.write("                 \r\n");
      out.write("                   <tr>\r\n");
      out.write("                    <td  align=\"left\">\r\n");
      out.write("                    <table border=\"0\" cellpadding=\"2\" cellspacing=\"0\" id=\"saleDetail_table\">\r\n");
      out.write("                        <tr bgcolor=\"#E6E6E6\">\r\n");
      out.write("                          <td align=\"center\" bgcolor=\"#EEEEEE\">序号</td>\r\n");
      out.write("\t\t\t\t\t\t\t  <td align=\"center\" bgcolor=\"#EEEEEE\">品种</td>\r\n");
      out.write("\t\t\t\t\t\t\t  <td align=\"center\" bgcolor=\"#EEEEEE\">厂家</td>\r\n");
      out.write("\t\t\t\t\t\t\t  <td align=\"center\" bgcolor=\"#EEEEEE\">规格</td>\r\n");
      out.write("\t\t\t\t\t\t\t  <td align=\"center\" bgcolor=\"#EEEEEE\">单位</td>\r\n");
      out.write("\t\t\t\t\t\t\t  <td align=\"center\" bgcolor=\"#EEEEEE\">批号</td>\r\n");
      out.write("\t\t\t\t\t\t\t  <td align=\"center\" bgcolor=\"#EEEEEE\">有效期</td>\r\n");
      out.write("\t\t\t\t\t\t\t  <td align=\"center\" bgcolor=\"#EEEEEE\">统一零售价</td>\r\n");
      out.write("\t\t\t\t\t\t\t   <td align=\"center\" bgcolor=\"#EEEEEE\">仓库</td>\r\n");
      out.write("\t\t\t\t\t\t\t  <td align=\"center\" bgcolor=\"#EEEEEE\">剩余库存</td>\r\n");
      out.write("\t\t\t\t\t\t\t  <td align=\"center\" bgcolor=\"#EEEEEE\">销售价</td>\r\n");
      out.write("\t\t\t\t\t\t\t  <td align=\"center\" bgcolor=\"#EEEEEE\">销售数量</td>\r\n");
      out.write("\t\t\t\t\t\t\t  <td align=\"center\" bgcolor=\"#EEEEEE\">销售金额</td>\r\n");
      out.write("\t\t\t\t\t\t\t  <td align=\"center\" bgcolor=\"#EEEEEE\">防伪号</td>\r\n");
      out.write("\t\t\t\t\t\t\t  <td width=16px;></td>\r\n");
      out.write("                        </tr>\r\n");
      out.write("                        <tr>\r\n");
      out.write("                          <td align=\"center\" colspan=\"20\" height=\"1\" bgcolor=\"#D8D8D8\"></td>\r\n");
      out.write("                        </tr>\r\n");
      out.write("                        <tbody id=\"add_saleDetail_table\">\r\n");
      out.write("\t                        <tr>\r\n");
      out.write("\t                            <td align=\"center\">\r\n");
      out.write("\t                                <input type=\"checkbox\" name=\"ck\"/>\r\n");
      out.write("\t                                <input type=\"hidden\" name=\"saleDetailList[0].stockkey\" />\r\n");
      out.write("\t                                <input type=\"hidden\" name=\"saleDetailList[0].articleid\" />\r\n");
      out.write("\t                            </td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td align=\"left\">\r\n");
      out.write("\t\t\t\t\t\t\t\t  <select id=\"stockinDetailList[0].articlename\" name=\"stockinDetailList[0].articlename\" type=\"text\"  class=\"easyui-combobox\" data-options=\"required:true,\r\n");
      out.write("\t\t \t\t\t\t\t\t        url:'saleAction!saleStockCombox.action',\r\n");
      out.write("\t\t\t\t\t\t\t\t      \tvalueField:'stockkey',\r\n");
      out.write("\t\t\t\t\t\t\t\t        textField:'articlename',\r\n");
      out.write("\t\t\t\t\t\t                panelHeight:90,\r\n");
      out.write("\t\t\t\t\t\t                panelWidth:650,\r\n");
      out.write("\t\t\t\t\t\t                filter: function(q, row){\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\tvar opts = $(this).combobox('options');\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\treturn row[opts.textField].indexOf(q)!=-1||row['articlealias'].indexOf(q)!=-1;\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t},\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tformatter:function(row){\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t   var factoryname = row.factory;\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t   if (row.factory.length>7) factoryname = row.factory.substring(0,7);\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t   var articlespec = row.articlespec;\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t   if (row.articlespec.length>12) articlespec = row.articlespec.substring(0,12);\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t   return '<table  class=comboxstock><tr><td >'+row.articlename+'</td><td width=110px;>'+row.articlespec+'</td><td width=100px;>'+row.factory+'</td><td width=50px;>'+row.num+'('+row.unitname+')</td><td width=80px>'+row.serial+'</td><td width=70px;>'+row.expiredate.substr(0,10)+'</td></tr></table>';\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t},\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tonSelect: function(rec){ \r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t     var stockkey = $(this).parent().prev().find('input[name*=\\'stockkey\\']').eq(0).val(rec.stockkey);\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t     var articleid = $(this).parent().prev().find('input[name*=\\'articleid\\']').eq(0).val(rec.articleid);\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t     var factory = $(this).parent().next().children('input').eq(0).val(rec.factory);\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t     var articlespec = $(this).parent().next().next().children('input').eq(0).val(rec.articlespec);\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t     var unitname = $(this).parent().next().next().next().children('input').eq(0).val(rec.unitname);\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t     var serial = $(this).parent().next().next().next().next().children('input').eq(0).val(rec.serial);\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t     var expiredate = $(this).parent().next().next().next().next().next().children('input').eq(0).val(rec.expiredate);\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t     var retailprice = $(this).parent().next().next().next().next().next().next().children('input').eq(0).val(rec.retailprice);\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t     var depotname = $(this).parent().next().next().next().next().next().next().next().children('input').eq(0).val(rec.depotname);\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t     var num = $(this).parent().next().next().next().next().next().next().next().next().children('input').eq(0).val(rec.num);\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t     //var saleprice = $(this).parent().next().next().next().next().next().next().next().next().next().children('input').eq(0).val(rec.pfprice);\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t     var salenum = $(this).parent().next().next().next().next().next().next().next().next().next().next().children('input').eq(0).numberbox('options').max = rec.num;\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t     //var salenum = $(this).parent().next().next().next().next().next().next().next().children('input').eq(0).focus();\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t     //alert($(this).parent().prev().find('input[name*=\\'stockkey\\']').eq(0).val());\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t}\r\n");
      out.write("\t\t \t\t\t\t\t\t       \"  missingMessage=\"请填写品种\"  style=\"width:165px;\" >\r\n");
      out.write("\t\t \t\t\t\t\t       </select>\r\n");
      out.write("\t\t\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td align=\"left\">\r\n");
      out.write("\t\t\t\t\t\t\t\t  <input name=\"factory\" readonly=\"readonly\"  maxlength=\"20\" type=\"text\" class=\"easyui-validatebox\" style=\"width:70px;\" >\r\n");
      out.write("\t\t\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td align=\"left\">\r\n");
      out.write("\t\t\t\t\t\t\t\t  <input name=\"articlespec\" readonly=\"readonly\"  maxlength=\"20\" type=\"text\" class=\"easyui-validatebox\" style=\"width:50px;\" >\r\n");
      out.write("\t\t\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td align=\"left\">\r\n");
      out.write("\t\t\t\t\t\t\t\t  <input name=\"unitname\" readonly=\"readonly\"  maxlength=\"20\" type=\"text\" class=\"easyui-validatebox\" style=\"width:30px;\" >\r\n");
      out.write("\t\t\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td align=\"left\">\r\n");
      out.write("\t\t\t\t\t\t\t\t  <input name=\"serial\" readonly=\"readonly\"  maxlength=\"20\" type=\"text\" class=\"easyui-validatebox\" style=\"width:70px;\" >\r\n");
      out.write("\t\t\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td align=\"left\">\r\n");
      out.write("\t\t\t\t\t\t\t\t  <input name=\"expiredate\" readonly=\"readonly\"  maxlength=\"20\" type=\"text\" class=\"easyui-validatebox\" style=\"width:65px;\" >\r\n");
      out.write("\t\t\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td align=\"left\">\r\n");
      out.write("\t\t\t\t\t\t\t\t  <input name=\"retailprice\" readonly=\"readonly\"  maxlength=\"20\" type=\"text\" class=\"easyui-validatebox\" style=\"width:60px;\" >\r\n");
      out.write("\t\t\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td align=\"left\">\r\n");
      out.write("\t\t\t\t\t\t\t\t  <input name=\"depotname\" readonly=\"readonly\"  maxlength=\"20\" type=\"text\" class=\"easyui-validatebox\" style=\"width:50px;\" >\r\n");
      out.write("\t\t\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td align=\"left\">\r\n");
      out.write("\t\t\t\t\t\t\t\t  <input name=\"stocknum\" readonly=\"readonly\" maxlength=\"20\" type=\"text\" class=\"easyui-validatebox\" style=\"width:50px;\" >\r\n");
      out.write("\t\t\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td align=\"left\">\r\n");
      out.write("\t\t\t\t\t\t\t\t  <input id=\"saleDetailList[0].saleprice\" name=\"saleDetailList[0].saleprice\"  maxlength=\"\" type=\"text\" data-options=\"required:true,precision:2\" class=\"easyui-numberbox\" style=\"width:50px;\" >\r\n");
      out.write("\t\t\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td align=\"left\">\r\n");
      out.write("\t\t\t\t\t\t\t\t   <input id=\"saleDetailList[0].num\" name=\"saleDetailList[0].num\" maxlength=\"\" type=\"text\" class=\"easyui-numberbox\" data-options=\"required:true,precision:0,min:0\"  style=\"width:50px;\" >\r\n");
      out.write("\t\t\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td align=\"left\">\r\n");
      out.write("\t\t\t\t\t\t\t\t   <input name=\"saleDetailList[0].amount\" onclick=\"computeAmount(this)\" readonly=\"readonly\" maxlength=\"\" type=\"text\"  data-options=\"precision:2\" style=\"width:50px;\" >\r\n");
      out.write("\t\t\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td align=\"left\">\r\n");
      out.write("\t\t\t\t\t\t\t\t   <input name=\"saleDetailList[0].secretno\" maxlength=\"50\" type=\"text\" class=\"easyui-validatebox\" data-options=\"required:true\" style=\"width:50px;\" >\r\n");
      out.write("\t\t\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td align=\"left\">\r\n");
      out.write("\t\t\t\t\t\t\t\t   <span class=\"calendar-menu-next\" onclick=\"findLastInprice(this)\" style=\"width:16px;\" ></span>\r\n");
      out.write("\t\t\t\t\t\t\t\t</td>\r\n");
      out.write("\t                        </tr>\r\n");
      out.write("                       </tbody>\r\n");
      out.write("                      </table>\r\n");
      out.write("                    </td>\r\n");
      out.write("                  </tr>\r\n");
      out.write("             \t </table> \r\n");
      out.write("\t\t\t  </div>\r\n");
      out.write("\t   </div>\r\n");
      out.write("\t\t\t<div align=\"center\">\r\n");
      out.write("\t\t\t\t<table width=\"100%;\">\r\n");
      out.write("                  <tr>\r\n");
      out.write("                    <td height=\"50\" colspan=\"8\"  align=\"center\">\r\n");
      out.write("                        <input value=\" 关 闭 \" type=\"button\" id=\"doReturn\"/>\r\n");
      out.write("                      \t<input value=\" 提 交 \" type=\"button\" onClick=\"dosubmit();\"  />\r\n");
      out.write("                    </td>\r\n");
      out.write("                  </tr>\r\n");
      out.write("                  <tr>\r\n");
      out.write("                     <td style=\"font-size:12px;color: blue;text-align:left;\">\r\n");
      out.write("                       注:行中的黑色箭头作用是根据当前的客户和当前行的品种查找客户最近一次的销售价格;\r\n");
      out.write("                     </td>\r\n");
      out.write("                  </tr>\r\n");
      out.write("              </table>\r\n");
      out.write("\t\t    </div>\t\r\n");
      out.write(" \t\t </form>\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("<table style=\"display:none\">\r\n");
      out.write("       <tbody id=\"add_saleDetail_table_template\">\r\n");
      out.write("          <tr>\r\n");
      out.write("\t                            <td align=\"center\">\r\n");
      out.write("\t                                <input type=\"checkbox\" name=\"ck\"/>\r\n");
      out.write("\t                                <input type=\"hidden\" name=\"saleDetailList[#index#].stockkey\" />\r\n");
      out.write("                                    <input type=\"hidden\" name=\"saleDetailList[0].articleid\" />\r\n");
      out.write("\t                            </td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td align=\"left\">\r\n");
      out.write("\t\t\t\t\t\t\t\t  <select id=\"stockinDetailList[#index#].articlename\" name=\"stockinDetailList[#index#].articlename\" type=\"text\"   data-options=\"required:true,\r\n");
      out.write("\t\t \t\t\t\t\t\t         url:'saleAction!saleStockCombox.action',\r\n");
      out.write("\t\t\t\t\t\t\t\t      \tvalueField:'stockkey',\r\n");
      out.write("\t\t\t\t\t\t\t\t        textField:'articlename',\r\n");
      out.write("\t\t\t\t\t\t                panelHeight:90,\r\n");
      out.write("\t\t\t\t\t\t                panelWidth:600,\r\n");
      out.write("\t\t\t\t\t\t                filter: function(q, row){\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\tvar opts = $(this).combobox('options');\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\treturn row[opts.textField].indexOf(q)!=-1||row['articlealias'].indexOf(q)!=-1;\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t},\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tformatter:function(row){\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t   return '<table  class=comboxstock><tr><td >'+row.articlename+'</td><td width=60px;>'+row.articlespec+'</td><td width=90px;>'+row.factory+'</td><td width=50px;>'+row.num+'('+row.unitname+')</td><td width=80px>'+row.serial+'</td><td width=70px;>'+row.expiredate.substr(0,10)+'</td></tr></table>';\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t},\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tonSelect: function(rec){ \r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t     var stockkey = $(this).parent().prev().find('input[name*=\\'stockkey\\']').eq(0).val(rec.stockkey);\r\n");
      out.write("                                             var articleid = $(this).parent().prev().find('input[name*=\\'articleid\\']').eq(0).val(rec.articleid);\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t     var factory = $(this).parent().next().children('input').eq(0).val(rec.factory);\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t     var articlespec = $(this).parent().next().next().children('input').eq(0).val(rec.articlespec);\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t     var unitname = $(this).parent().next().next().next().children('input').eq(0).val(rec.unitname);\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t     var serial = $(this).parent().next().next().next().next().children('input').eq(0).val(rec.serial);\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t     var expiredate = $(this).parent().next().next().next().next().next().children('input').eq(0).val(rec.expiredate);\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t     var retailprice = $(this).parent().next().next().next().next().next().next().children('input').eq(0).val(rec.retailprice);\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t     var depotname = $(this).parent().next().next().next().next().next().next().next().children('input').eq(0).val(rec.depotname);\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t     var num = $(this).parent().next().next().next().next().next().next().next().next().children('input').eq(0).val(rec.num);\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t     //var saleprice = $(this).parent().next().next().next().next().next().next().next().next().next().children('input').eq(0).val(rec.pfprice);\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t     var salenum = $(this).parent().next().next().next().next().next().next().next().next().next().next().children('input').eq(0).numberbox('options').max = rec.num;\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t     //var salenum = $(this).parent().next().next().next().next().next().next().next().children('input').eq(0).focus();\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t     //alert($(this).parent().prev().find('input[name*=\\'stockkey\\']').eq(0).val());\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t}\r\n");
      out.write("\t\t \t\t\t\t\t\t       \"  missingMessage=\"请填写品种\"  style=\"width:165px;\" >\r\n");
      out.write("\t\t \t\t\t\t\t       </select>\r\n");
      out.write("\t\t\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td align=\"left\">\r\n");
      out.write("\t\t\t\t\t\t\t\t  <input name=\"factory\" readonly=\"readonly\"  maxlength=\"20\" type=\"text\" class=\"easyui-validatebox\" style=\"width:70px;\" >\r\n");
      out.write("\t\t\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td align=\"left\">\r\n");
      out.write("\t\t\t\t\t\t\t\t  <input name=\"articlespec\" readonly=\"readonly\"  maxlength=\"20\" type=\"text\" class=\"easyui-validatebox\" style=\"width:50px;\" >\r\n");
      out.write("\t\t\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td align=\"left\">\r\n");
      out.write("\t\t\t\t\t\t\t\t  <input name=\"unitname\" readonly=\"readonly\"  maxlength=\"20\" type=\"text\" class=\"easyui-validatebox\" style=\"width:30px;\" >\r\n");
      out.write("\t\t\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td align=\"left\">\r\n");
      out.write("\t\t\t\t\t\t\t\t  <input name=\"serial\" readonly=\"readonly\"  maxlength=\"20\" type=\"text\" class=\"easyui-validatebox\" style=\"width:70px;\" >\r\n");
      out.write("\t\t\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td align=\"left\">\r\n");
      out.write("\t\t\t\t\t\t\t\t  <input name=\"expiredate\" readonly=\"readonly\"  maxlength=\"20\" type=\"text\" class=\"easyui-validatebox\" style=\"width:65px;\" >\r\n");
      out.write("\t\t\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td align=\"left\">\r\n");
      out.write("\t\t\t\t\t\t\t\t  <input name=\"retailprice\" readonly=\"readonly\"  maxlength=\"20\" type=\"text\" class=\"easyui-validatebox\" style=\"width:60px;\" >\r\n");
      out.write("\t\t\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td align=\"left\">\r\n");
      out.write("\t\t\t\t\t\t\t\t  <input name=\"depotname\" readonly=\"readonly\"  maxlength=\"20\" type=\"text\" class=\"easyui-validatebox\" style=\"width:50px;\" >\r\n");
      out.write("\t\t\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td align=\"left\">\r\n");
      out.write("\t\t\t\t\t\t\t\t  <input name=\"stocknum\" readonly=\"readonly\" maxlength=\"20\" type=\"text\" class=\"easyui-validatebox\" style=\"width:50px;\" >\r\n");
      out.write("\t\t\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td align=\"left\">\r\n");
      out.write("\t\t\t\t\t\t\t\t  <input id=\"saleDetailList[#index#].saleprice\" name=\"saleDetailList[#index#].saleprice\"  maxlength=\"\" type=\"text\" data-options=\"required:true,precision:2\"  style=\"width:50px;\" >\r\n");
      out.write("\t\t\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td align=\"left\">\r\n");
      out.write("\t\t\t\t\t\t\t\t   <input id=\"saleDetailList[#index#].num\" name=\"saleDetailList[#index#].num\" maxlength=\"\" type=\"text\"  data-options=\"required:true,precision:0,min:0\"  style=\"width:50px;\" >\r\n");
      out.write("\t\t\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td align=\"left\">\r\n");
      out.write("\t\t\t\t\t\t\t\t   <input name=\"saleDetailList[#index#].amount\" onclick=\"computeAmount(this)\" readonly=\"readonly\" maxlength=\"\" type=\"text\"  data-options=\"precision:2\" style=\"width:50px;\" >\r\n");
      out.write("\t\t\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td align=\"left\">\r\n");
      out.write("\t\t\t\t\t\t\t\t   <input name=\"saleDetailList[#index#].secretno\" maxlength=\"50\" type=\"text\" class=\"easyui-validatebox\" data-options=\"required:true\" style=\"width:50px;\" >\r\n");
      out.write("\t\t\t\t\t\t\t\t</td>\r\n");
      out.write("                                <td>\r\n");
      out.write("\t\t\t\t\t\t\t\t   <span class=\"calendar-menu-next\" onclick=\"findLastInprice(this)\" style=\"width:16px;\"></span>\r\n");
      out.write("\t\t\t\t\t\t\t\t</td>\r\n");
      out.write("\t                        </tr>\r\n");
      out.write("      </tbody>\r\n");
      out.write("</table>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
